### ISSUE TITLE
sticky toc

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#1]
Hi @stefanprobst ,

I implemented the tables yesterday, that was very easy. But the sticky TOC is a little more difficult for me to get exactly right, so it would be great if you could do it.

Just as a reminder:
-  we want the toc to be sticky, i.e. stuck to the top of the page on scroll down on wide screens
- we want it to stay where it is now (after the metadata) on mobile and tablets.

Similar to this https://www.gatsbyjs.org/docs/adding-search-with-algolia/ 

I hope Berlin is treating you well. Say hi to the other SSHOCers. 

All best,
T.

**Comment by stefanprobst** [comment]
TODO:

* [x] scrollable sidebar TOC

**Comment by stefanprobst** [comment]
toc sidebar is updated and hopefully scrolls correctly now
