### ISSUE TITLE
Building DC on an M1 Mac

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#101]
Hi Stefan.

I have a new shiny laptop which has Apple's M1 processor. `yarn install` fails with the following message:

```
error /Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-darwin-arm64v8.tar.gz
ERR! sharp Prebuilt libvips binaries are not yet available for darwin-arm64v8
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
```

The full log is here https://gist.github.com/ttasovac/48c004e14a2c832f9b213d0b4045230e. 

Now based on https://github.com/lovell/sharp/issues/2614, the latest version of Gatsby is using the latest version of sharp so I'm hoping that that would solve my M1-related problems. I don't dare mess around with dependencies though on my own because I don't want to screw things up. 

When you have a moment, could you please try to update our gatsby package so that I can test to see whether that resolves my issues on the M1 Mac.

Many thanks in advance.

All best,
Toma

**Comment by stefanprobst** [comment]
this will be fixed in the new dc version

**Comment by ttasovac** [comment]
ok!
