### ISSUE TITLE
[new resource]: Why Space is Special: An Introduction into GIS and Geospatial History

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#1012]
### Title of the resource

Why Space is Special: An Introduction into GIS and Geospatial History

### Resource type

Hosted Resource

### Authors, editors and contributors

Emily Genatowski, Liam Downs-Tepper

### Topics (keywords)

GIS

### Learning outcomes

Students should be able to understand a broad overview of GIS, it's uses and how it operates
Students should have a broad overview of the history of geospatial history

### Abstract

In completing this resource, students will be able to understand the importance of space, the foundational operations and uses of GIS as well as the history of Geospatial science.

**Comment by emilykateemilykate** [comment]
a contributor to this resource is named  Liam Downs-Tepper

**Comment by VickyGarnett** [comment]
resource published, closing issue
