### ISSUE TITLE
[new resource]: A Non-Technical Guide to Technical GIS Methods

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#1013]
### Title of the resource

A Non-Technical Guide to Technical GIS Methods 

### Resource type

None

### Authors, editors and contributors

Emily Genatowski, Liam Downs-Tepper

### Topics (keywords)

GIS 

### Learning outcomes

Students should have an understanding of how the GIS methods work and what they can accomplish through the use of the technical methods

### Abstract

This resource serves as an approachable guide to the technical world of GIS.  Learn how the process works and enjoy an an overview how to interact with the tools and methods.

**Comment by VickyGarnett** [comment]
resource published, closing issue
