### ISSUE TITLE
[new resource]: Here There be Monsters: Maps as a Narrative Tool

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#1014]
### Title of the resource

Here There be Monsters: Maps as a Narrative Tool 

### Resource type

None

### Authors, editors and contributors

Emily Genatowski, Liam Downs-Tepper

### Topics (keywords)

GIS

### Learning outcomes

Students completing this resource should be able to understand how and why to utilize maps as a narrative tool in their projects and research.

### Abstract

Learn how and when to utilize mapping in your research and storytelling.  Understand the tools and context of including maps in research and publication.

**Comment by VickyGarnett** [comment]
resource published, closing issue
