### ISSUE TITLE
[new resource]: Google My Maps for Everyday Use: A Tutorial 

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#1015]
### Title of the resource

Google My Maps for Everyday Use: A Tutorial  

### Resource type

None

### Authors, editors and contributors

Emily Genatowski, Liam Downs-Tepper

### Topics (keywords)

GIS 

### Learning outcomes

Students should understand existing open source mapping tools and how to incorporate geospatial science into their work.

### Abstract

Understand open source mapping tools and learn the value of incorporating geospatial science into your life and research.

**Comment by VickyGarnett** [comment]
resource published, closing issue
