### ISSUE TITLE
[new resource]: Data and Databases: An Introduction

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#1043]
### Title of the resource

Data and Databases: An Introduction 

### Resource type

Hosted Resource

### Authors, editors and contributors

Emily Genatowski, James Baille

### Topics (keywords)

Data, Databases

### Learning outcomes

Upon completion of this resource, learners should be able to:
Identify what a database is and how it is used in humanities research
Discuss examples of Humanities Databases
Understand when a researcher would need to use a database
Distinguish between database technologies

### Abstract

In this resource students will learn what a database is and how it is used in humanities research, go through examples of Humanities Databases in use by researchers today, learn when a researcher would need to use a database and how to distinguish between different database technologies!

**Comment by emilykateemilykate** [comment]
Just wanted to let you know as I know we have discussed the order of things that the full data and databases text was submitted to me before the full GIS text so although I submitted the GIS new resource requests, I am in possession of the full data and databases text from James Baille and would love to begin arranging it on the cms as I wait for the final text submission from the GIS author.  

I apologize for the timing.  I was not made aware of the order when I submitted for the GIS ones first.

**Comment by emilykateemilykate** [comment]
[Chapter 01 Introduction.pdf](https://github.com/DARIAH-ERIC/dariah-campus/files/15405893/Chapter.01.Introduction.pdf)
Here is an example of the full text I was given in order to begin putting it on the cms backend. I have this for the database course already but not yet the GIS, hence the request.  Just wanted to clarify.

**Comment by VickyGarnett** [comment]
resource published, closing issue
