### ISSUE TITLE
When my pull request would be merged?

### ISSUE THREAD

**Issue by mashalahmad** [DARIAH-ERIC/dariah-campus#105]
Hi I submit a pull request 11 days ago but it still isnt merged. Can you please tell any update on it?

[https://github.com/DARIAH-ERIC/dariah-campus/pull/100](https://github.com/DARIAH-ERIC/dariah-campus/pull/100)

**Comment by VickyGarnett** [comment]
Hi Mashal - Thanks for your message.  We've received your Pull Request, and I have it on my list to review.  We've received a greater number of pull requests than usual in the last few weeks, so are running a bit behind.  But don't worry - we've got it!
Thanks - Vicky
