### ISSUE TITLE
503 Service Temporarily Unavailable for "Digital Scholarly Editions: Manuscripts, Texts and TEI Encoding" resource

### ISSUE THREAD

**Issue by carikan** [DARIAH-ERIC/dariah-campus#1050]
### Bug report

I wanted to see the resource for this course, upon clicking g" go to this resource", the error "503 Service Temporarily Unavailable" appears. It is the same case for the courses "Text Encoding and the Text Encoding Initiative" and "Digitising Dictionaries".

**Comment by stefanprobst** [comment]
please provide the links you were trying to click.

**Comment by ttasovac** [comment]
These are remote resources hosted on DARIAH Teach. The problem is on their server and you will need to contact somebody from the #dariahTeach team. https://teach.dariah.eu is down. @stefanprobst could you pass this on to whomever is in charge of it.

**Comment by carikan** [comment]
> please provide the links you were trying to click.

https://teach.dariah.eu/course/view.php?id=32

**Comment by vronk** [comment]
Service is temporarily unavailable due to maintenance.
Should be back again in the course of today.

**Comment by carikan** [comment]
Works fine again
