### ISSUE TITLE
Link broken / not existing on video documentation page

### ISSUE THREAD

**Issue by yoannspace** [DARIAH-ERIC/dariah-campus#106]
The link to the "Sample-resource template" in the video sub chapter is broken: https://github.com/DARIAH-ERIC/dariah-campus/blob/master/documentation/doing-the-work.mdx#videos

**Comment by yoannspace** [comment]
Came up because we would like to know if we can add other video resources (not from Youtube), e.g. from nakala.fr with "embedded" links

**Comment by ttasovac** [comment]
thanks @yoannspace 

@VickyGarnett could you please put this on your todo list (not for today or tomorrow :) —  it probably doesn't make sense to have a link there anyway, but just explain again where the template file can be found. Also, I'm not even sure what "other options for inserting videos" are so please explore what this is about. 

@yoannspace At the moment, D-C allows only YouTube videos as embedded links —  all it takes is the id of the YouTube video source. This is, of course, not ideal.  @stefanprobst is currently working on the DARIAH-Campus CMS, so we may actually use this opportunity to add other video sources.

Stefan is super busy at the moment, so I can't promise anything right away. But please send us more info —  can we build URLs for direct access to videos on Nakala based on the video's ID alone?

@stefanprobst we can talk about this next Tuesday. Princeton would like to use Vimeo for the videos for our NLP workshop, so we would face this issue sooner or later...

**Comment by yoannspace** [comment]
Thanks @ttasovac 


Quickly about other sources: when I look at the way you insert [YouTube videos](https://github.com/DARIAH-ERIC/dariah-campus/blob/master/src/components/Youtube/Youtube.js), it seems you are using an "embed" link anyway, very much like Vimeo or Nakala provides, e.g. [nakala embed link](https://api.nakala.fr/embed/10.34847/nkl.f734kiqd/4701b123138c721007562e3caacecd6a208d329f) coming from the [dataset](https://nakala.fr/10.34847/nkl.f734kiqd)

So yes, I really imagine the change to be very simple - only the documentation would need to be changed so that the full URL is provided and not the YouTube id. And since you curate everything, you will definitely be able to find out if someone provided a wrong/bad link.

**Comment by ttasovac** [comment]
cool. we'll look into this.
