### ISSUE TITLE
Citation for DRI resources missing remote publisher

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#108]
Dear @VickyGarnett,

make sure to always check the citation widget after publication to see if it's correct. The DRI resources look like this:

![Снимок экрана 2021-06-11 в 15 52 37](https://user-images.githubusercontent.com/5304839/121697248-29017580-cacd-11eb-9f82-032fe8e092dd.png)

When you see something like this, it means that a piece of metadata is missing, in this particular case: `remotePublisher` which should be Digital Repository of Ireland. Also, since we should include DRI as a remote publisher, we shouldn't really include it as the first author. But, perhaps, that's a temporary solution until we get the Curricula implemented.

@mashalahmad Vicky's away next week —  would you be able to submit a pull request with the DRI resources adding the remote publisher metadata field as explained here: https://campus.dariah.eu/docs/doing-the-work#setting-the-metadata-for-citation 

—  also, I would remove DRI as the author... but perhaps you decided to have it like that on purpose... so we can revisit that question when Vicky comes back.

All best,
Toma

**Comment by mashalahmad** [comment]
Hi @ttasovac  I will have a look at it sorry for late reply. Will push the changes soon :)
