### ISSUE TITLE
Missing data and download file in XPath lesson?

### ISSUE THREAD

**Issue by yoannspace** [DARIAH-ERIC/dariah-campus#109]
Via Helpdesk, someone mentioned not being able to find the XML file to follow the lesson. Might be something missing here https://github.com/DARIAH-ERIC/dariah-campus/blob/master/contents/resources/xpath-for-dictionary-nerds/index.mdx#what-do-i-need-to-work-with-xpath - it says `Download XXXXXX`.
@VickyGarnett is set to answer the Helpdesk request, but that bug might be for @ttasovac

**Comment by VickyGarnett** [comment]
Hi Yoann,

Thanks for pointing this out.  Unfortunately I can't help with this as Toma wrote it, and I don't know which resource it needs to point to.  I'll raise it with him though.  Thanks :)

**Comment by stefanprobst** [comment]
@ttasovac there's also two TODO comments [here](https://github.com/DARIAH-ERIC/dariah-campus/blob/e4059feddcd82f143679c4fc5ee3b68db166255d/content/posts/xpath-for-dictionary-nerds/index.mdx#L195) and [here](https://github.com/DARIAH-ERIC/dariah-campus/blob/e4059feddcd82f143679c4fc5ee3b68db166255d/content/posts/xpath-for-dictionary-nerds/index.mdx#L360)

**Comment by VickyGarnett** [comment]
This got solved didn't it?  can I close this issue down now? @ttasovac @stefanprobst

**Comment by ttasovac** [comment]
yes
