### ISSUE TITLE
[new resource]: Creating GUIs in Python for Digital Humanities Projects

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#1092]
### Title of the resource

Creating GUIs in Python for Digital Humanities Projects

### Resource type

External Resource

### Authors, editors and contributors

Christopher Goodwin, Yann Ryan, Telma Peura, Liz Fischer

### Topics (keywords)

DH, Open Education, Open Access, python, data management

### Learning outcomes

This lesson uses Python to create a program with a GUI interface that can merge multiple PDF documents into a single PDF file. The main goal is to learn the basics of creating GUIs. By the end of this lesson, you will be able to:

- Design a GUI using proven design principles of user-friendliness
- Create a GUI using Qt Designer
- Implement a GUI within a Python script
- Build a distributable application version of your script

### Abstract

In this lesson, you will use Qt Designer and Python to design and implement a simple graphical user interface and application to merge PDF files. This lesson also demonstrates how to package the application for distribution to other personal computers.

**Comment by VickyGarnett** [comment]
Hi Charlotte - these people are all in the system now, so you can continue to draft up the resource :)

**Comment by VickyGarnett** [comment]
resource published, closing issue
