### ISSUE TITLE
[new resource]: Creating Deep Convolutional Neural Networks for Image Classification

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#1093]
### Title of the resource

Creating Deep Convolutional Neural Networks for Image Classification

### Resource type

External Resource

### Authors, editors and contributors

Nabeel Siddiqui, Scott Kleinman, Fabian Offert, Melvin Wevers

### Topics (keywords)

DH, Open Education, Open Access, Machine Learning

### Learning outcomes

After completing this lesson, you will be able to:
- understand how convolutional neural networks function 
- train and use them to perform image classification on paintings
- embed a model on live website

### Abstract

This lesson provides a beginner-friendly introduction to convolutional neural networks (CNNs) for image classification. The tutorial provides a conceptual understanding of how neural networks work by using Google’s Teachable Machine to train a model on paintings from the ArtUK database. This lesson also demonstrates how to use Javascript to embed the model in a live website.

**Comment by VickyGarnett** [comment]
Hi Charlotte - these people are all in the system, so you can continue to draft the resource :)

**Comment by VickyGarnett** [comment]
resource published, closing issue
