### ISSUE TITLE
[new resource]: Transcribing Handwritten Text with Python and Microsoft Azure Computer Vision

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#1098]
### Title of the resource

Transcribing Handwritten Text with Python and Microsoft Azure Computer Vision

### Resource type

None

### Authors, editors and contributors

Jeff Blackadar, Maria Dermentzi, Megan S. Kane, Giulia Taurino

### Topics (keywords)

DH, Open Education, Open Access, python, api, data manipulation

### Learning outcomes

After completing this lesson, you will be able to:
- Write a Python program to transcribe images of handwritten documents using Microsoft’s Azure Cognitive Services, a commercially available service that has a cost-free option for low volumes of use
- Add steps to process multiple images at once and store the transcribed text in a file
- Better organise your code using a Python function

### Abstract

Tools for machine transcription of handwriting are practical and labour-saving if you need to analyse or present text in digital form. This lesson will explain how to write a Python program to transcribe handwritten documents using Microsoft’s Azure Cognitive Services, a commercially available service that has a cost-free option for low volumes of use.

**Comment by VickyGarnett** [comment]
Hi @charlottejmc  - these people are all in the system, so you can continue to draft the resource :)

**Comment by VickyGarnett** [comment]
resource published, closing issue
