### ISSUE TITLE
Introduction to Collections as data

### ISSUE THREAD

**Issue by hibernator11** [DARIAH-ERIC/dariah-campus#1107]
### Title of the resource

Introduction to Collections as data

### Resource type

Hosted Resource

### Authors, editors and contributors

Gustavo Candela, Vicky Dritsou, Agiatis Benardou, Sally Chambers, Alba Irollo, Toma Tasovac

### Topics (keywords)

Digital collections, Computational access, GLAM, Cultural Heritage

### Learning outcomes

Upon completion of this course, participants will be able to: 

- create awareness of the relevance Collections as Data in the context of GLAM; 
- appreciate the complexity of Collections as Data; 
- analyse the structure of a digital collection suitable for computational use; 
- understand the steps involved when publishing collections as data.

### Abstract

The goal of this course is to introduce the Collections as Data principles in the context of GLAM (Galleries, Libraries, Archives and Museums) and to analyse the different aspects to consider when making available a digital collection suitable for computational use. In order to do so, the course will cover a selection of relevant facets to publish collections as data such as providing a licence, terms of use, documentation and examples of use, or using a platform to make available the collection. At the end of this course, students will have a fundamental understanding of the complexities of Collections as Data as well as an appreciation of the diversity of the content provided by GLAM institutions. This lesson will be useful for anyone wishing to improve their knowledge about Collections as Data as well as small and medium-sized GLAM institutions willing to make available their digital collections suitable for computational use. Additionally, it will provide Collections as Data examples provided by relevant institutions.

**Comment by VickyGarnett** [comment]
Hi @hibernator11 - The authors are now all in the system.

Looking at the proposed tags here, I think you can probably use 'Repositories & Collections' rather than creating 'Digital Collections' and 'GLAM'.  However I think there is value in creating 'Cultural Heritage' in addition to the existing 'eHeritage' (which I also recommend you use for this.  If you can send me a very short (20 words max) definition for 'Cultural Heritage' that would be great.

You can proceed to drafting this resource now.

Thanks!

Vicky

**Comment by hibernator11** [comment]
Hi @VickyGarnett 

Thank you very much for the information. We can use "Repositories & Collections" instead of 'Digital Collections' and 'GLAM'. 

With regard to the definition of Cultural Heritage, could it work this one provided by UNESCO?

https://uis.unesco.org/en/glossary-term/cultural-heritage

"Cultural heritage includes artefacts, monuments, a group of buildings and sites, museums that have a diversity of values including symbolic, historic, artistic, aesthetic, ethnological or anthropological, scientific and social significance. It includes tangible heritage (movable, immobile and underwater), intangible cultural heritage (ICH) embedded into cultural, and natural heritage artefacts, sites or monuments."

Best,
Gustavo

**Comment by VickyGarnett** [comment]
Hi @hibernator11 ,

Thanks for this!  That definition is great, but unfortunately far too long!  If you can whittle that down to 20 words that would be great!!  Thanks :). VG

**Comment by hibernator11** [comment]
Hi @VickyGarnett,

What about something like this (with Sally’s help 😊):

“Cultural Heritage includes material objects such as paintings, manuscripts and buildings, and intangible heritage like historical traditions and rituals.”

I hope it is useful.

Best,
Gustavo

**Comment by hibernator11** [comment]
Hi @VickyGarnett,

We have made small changes concerning the title (only a capital letter), keywords and learning outcomes. I hope it is ok.

**Title of the resource:** Introduction to Collections as Data

**Topics (keywords):** Cultural Heritage, Repository & Collections, Data Management, FAIR 

**Learning outcomes:**
 Upon completion of this course, participants will be able to: 
- understand the relevance of Collections as Data in the context of the cultural heritage sector; 
- appreciate the complexity of Collections as Data; 
- analyse the structure of a digital collection suitable for computational use; 
- understand the steps involved when publishing collections as data.

Best,
Gustavo

**Comment by VickyGarnett** [comment]
resource published, closing issue
