### ISSUE TITLE
[new resource]: Introduction to Cultural Heritage Data

### ISSUE THREAD

**Issue by vdritsou** [DARIAH-ERIC/dariah-campus#1108]
### Title of the resource

Introduction to Cultural Heritage Data

### Resource type

Hosted Resource

### Authors, editors and contributors

Vicky Dritsou, Agiatis Benardou, Gustavo Candela, Sally Chambers, Alba Irollo, Toma Tasovac

### Topics (keywords)

Cultural Heritage, CH Data, DH

### Learning outcomes

Upon completion of this course, participants will: 

- understand the significance of Cultural Heritage Data;
- know the different types of CH data and their common formats;
- identify the sources where CH data can be acquired from; 
- be familiar with digital methods and techniques that improve CH data quality; 
- know the basic structures and the metadata standards that CH data can be organised in; 
- understand the significance and the challenges of their preservation and access.

### Abstract

This course gives the knowledge and skills for understanding and efficiently using Cultural Heritage (CH) Data. Participants follow Prof. Lorena, a fictional academic persona, to learn about the significance, types, and formats of CH data. They are introduced to identifying CH data sources, enhancing data quality, and organizing data for preservation and access. The course also covers CH metadata standards and explores current trends and technologies in the field.

**Comment by VickyGarnett** [comment]
Hi @vdritsou - these authors are now all in the system.  I've already messaged Gustavo about proposed new tags.  I think Cultural Heritage is worth adding.

You can continue to the CMS now to draft this up.

Thanks

Vicky G!
