### ISSUE TITLE
test vicky

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#112]
test

**Comment by stefanprobst** [comment]
can this be closed?

**Comment by ttasovac** [comment]
@VickyGarnett is supposed to close it after she checks whether she got the initial notification for the new issue...

**Comment by VickyGarnett** [comment]
Yes - I just got this through.  Took a while.  Closing now.

**Comment by stefanprobst** [comment]
if you think it makes sense we can add default `assignees` to proposals for new resources.

**Comment by ttasovac** [comment]
I think that may be a good idea —  it looks like Vicky is only getting notifications if she gets mentioned explicitly, but not on every new issue (which is strange, I thought she and i had the same repo rights...) anyway, let's check it out in... ooops... only two minutes until our meeting!!!?? :) 
--
Belgrade Center for Digital Humanities
http://humanistika.org
