### ISSUE TITLE
Digital Exhibition Design

### ISSUE THREAD

**Issue by msamaroudi** [DARIAH-ERIC/dariah-campus#1140]
### Title of the resource

Digital Exhibition Design

### Resource type

External Resource

### Authors, editors and contributors

Myrsini Samaroudi

### Topics (keywords)

digital exhibitions, exhibition design, multimedia application design, heritage applications, digital interpretation

### Learning outcomes

- Manage a digital exhibition/experience project.
- Define users or target audiences through UX and visitor research methods.
- Design a storyboard for a multimedia interpretative application.

### Abstract

https://universityofbrighton.github.io/2023-exhibition-design/

This resource provides guidance on digital practices to curate interactive experiences through a set of practical exercises. The resource aims to support GLAM’s researchers and practitioners to engage with their audiences through the design of multimedia applications, while making use of appropriate frameworks and tools.

**Comment by VickyGarnett** [comment]
Hi Myrsini,

Your name is now in the system, so you can proceed to start drafting this resource up.

Regarding tags (topics/keywords), I recommend using 'eHeritage' and the soon-to-be-added 'Cultural Heritage' for this resource.  We do keep them very high level to avoid too many niche tags within only 1 resource each.

Thanks

Vicky
