### ISSUE TITLE
FAIR Multidimensional Data

### ISSUE THREAD

**Issue by msamaroudi** [DARIAH-ERIC/dariah-campus#1141]
### Title of the resource

FAIR Multidimensional Data

### Resource type

External Resource

### Authors, editors and contributors

Karina Rodriguez Echavarria

### Topics (keywords)

linked data, multidimensional media, arts and humanities, storytelling, virtual research environment

### Learning outcomes

- Define the different types of multidimensional media.
- Recognise the advantages of delivering and retrieving multidimensional content over the web via URLs and PIDs.
- Reflect on FAIR and CARE principles and their application on digital heritage research data.
- Understand the usefulness of Virtual Research Environments (VRE) and deploy VREs to support retrieval and curation of multidimensional data for storytelling via interoperable frameworks.

### Abstract

https://universityofbrighton.github.io/2023-fair-multidimensional-media/

This resource offers a starting point to learn more about the different types of multidimensional media, as well as managing media in a way which promotes the FAIR principles.
The resource also introduces the concept of a Virtual Research Environment to support retrieval and curation of multidimensional data for storytelling via interoperable frameworks.

**Comment by VickyGarnett** [comment]
Hi Myrsini - all the necessary info for this resource is now in the system, you can proceed to drafting this up on the content management system.

Do let me know if you have any questions.

Thanks - V :)

**Comment by VickyGarnett** [comment]
resource published, closing issue
