### ISSUE TITLE
Data Ethics in Cultural Heritage

### ISSUE THREAD

**Issue by msamaroudi** [DARIAH-ERIC/dariah-campus#1145]
### Title of the resource

Data Ethics in Cultural Heritage

### Resource type

External Resource

### Authors, editors and contributors

Myrsini Samaroudi

### Topics (keywords)

data ethics, ethics, research ethics, repatriation, human remains, environmental responsibility, participatory research

### Learning outcomes

- Identify and provide examples of some ethical considerations that arise in the context of research.
- Examine information documenting actual visual digital data in repositories and contrast it with ethical considerations.
- Critically assess ethical implications arising from cases in the digital heritage domain, suggesting how this could affect the discourse around ethics.

### Abstract

https://culturedigitalskills.github.io/2024-ethics-data/

This resource aims to introduce the main aspects of data ethics in the cultural heritage domain. It also examines how data management can be supported to become more ethical, while also addressing topical discourse about data ethics in the sector. The resource also aims to support in critically reflecting on some case studies with evident digital data ethics considerations.

**Comment by VickyGarnett** [comment]
Hi Myrsini - very excited to see this going up on Campus!  I'm happy for you to proceed to add this in the CMS.  We don't currently have a tag for 'Research Ethics', however it's an area I am very interested in and I think there are a few existing resources in the system that could benefit from this tag, so I will look into adding that one for you to use here.  Thanks - Vicky :)

**Comment by VickyGarnett** [comment]
resource published, closing issue
