### ISSUE TITLE
Copyright of 3D Data

### ISSUE THREAD

**Issue by msamaroudi** [DARIAH-ERIC/dariah-campus#1146]
### Title of the resource

Copyright of 3D Data

### Resource type

External Resource

### Authors, editors and contributors

Karina Rodriguez Echavarria, Myrsini Samaroudi

### Topics (keywords)

copyright, licensing, creative commons, UK law

### Learning outcomes

- Outline the ways in which creative works, in particular images and visual material are protected, in the context of copyright law in the UK.
- Understand and discuss the impact of the copyright legislation on personal practice for collecting multidimensional data.
- Compare the types of licenses available to protect and use creative works.
- Trial and give examples of Creative Commons licenses that could be applied to your work.

### Abstract

https://culturedigitalskills.github.io/2024-copyright-data/

This resource offers an introduction to copyright within the UK context when dealing with multidimensional media.

**Comment by VickyGarnett** [comment]
Hi Myrsini - I'm happy for you to proceed with drafting up this resource.  I would ask though that you mention in the descriptive content that this is specific to UK Law, but it also raises issues that may be relevant to learners in other countries.

Thanks!  V :)

**Comment by VickyGarnett** [comment]
resource published, closing issue
