### ISSUE TITLE
Metadata presentation

### ISSUE THREAD

**Issue by VickyGarnett** [DARIAH-ERIC/dariah-campus#115]
### Bug report

Hi Stefan,

I've noticed the metadata for resources is showing probably more information than is needed in the 'Published' field.

I've attached a screengrab.  Ideally I think we only need the YYYY-MM-DD info.

Thanks!

Vicky

<img width="1280" alt="Screenshot 2021-08-23 at 15 40 01" src="https://user-images.githubusercontent.com/57193002/130467585-e7ef56e1-6071-47e4-9dd8-467dcf29c04c.png">

**Comment by stefanprobst** [comment]
thanks for reporting, should be fixed now!

**Comment by VickyGarnett** [comment]
Hmmm - still seems to be showing the full timestamp :/

**Comment by stefanprobst** [comment]
it needs a couple of minutes to be deployed.

![Screenshot_20210823_170716](https://user-images.githubusercontent.com/20753323/130471189-7ab90895-7cb3-4aab-926a-83ba2bd79d4d.png)

**Comment by VickyGarnett** [comment]
Ah yes, am seeing it now.  Thanks! :)
