### ISSUE TITLE
elexis draft content

### ISSUE THREAD

**Issue by stefanprobst** [DARIAH-ERIC/dariah-campus#1162]
@ttasovac what is the status of these three resources, which all still have `draft: true`:

- https://github.com/DARIAH-ERIC/dariah-campus/blob/main/content/posts/mastering-lex1-the-dictionary-matrix/index.mdx?plain=1
- https://github.com/DARIAH-ERIC/dariah-campus/blob/main/content/posts/transforming-lexical-data-xslt-for-dictionary-nerds/index.mdx?plain=1
- https://github.com/DARIAH-ERIC/dariah-campus/blob/main/content/posts/modeling-dictionaries-in-tei-lex-0/index.mdx?plain=1

**Comment by ttasovac** [comment]
they were never completed. the tei lex-0 and xslt one i plan to complete for sure, but the dictionary matrix one i would have to check with the authors. the project is over so this is not a high priority. for now, i would like to keep them in draft status.
