### ISSUE TITLE
[new resource]: ENCODE #dariahTeach course

### ISSUE THREAD

**Issue by fosco13** [DARIAH-ERIC/dariah-campus#1166]
### Title of the resource

ENCODE course: Digital tools for the research and study of ancient writing cultures

### Resource type

External Resource

### Authors, editors and contributors

Tom Gheldof, Carla Salvaterra, Marta Fogagnolo, Alice Bencivenni, Marta Legnini, Massimo Magnani, Holger Essler, Nicola Reggiani, Marzia D'Angelo, Federica Nicolardi, Federico Aurora, Andrea Gasparini, Alessandro Palumbo, Mark Depauw, Pietro Liuzzo

### Topics (keywords)

Controlled Vocabularies, Data modeling, DH, Editing tools, eHeritage, Metadata, MOOC, Research infrastructures, Scholarly editions, Semantic web, Sustainability, TEI, Training and education, XML, XPath, XSLT

### Learning outcomes

At the end of this online course, participants will:

- **understand the digital transformations** in the field of Greek and Latin epigraphy, Papyrology and more in general in the field of Ancient Writing Cultures;
- **be familiar with digital projects** in the field and be motivated to go beyond the front end to discover their structures;
- **practice** some essential activities to participate in digital infrastructures and sharing research data (producing and sharing digital editions and FAIR data, structuring and connecting data, contextualizing information, disseminating open knowledge related to ancient written cultural heritage);
- **identify and choose the teaching and learning resources** that can help to upskill competences related to ancient written objects on the digital side;
- **manage tools to integrate digital competences** in the teaching and learning of Greek and Latin Epigraphy, Papyrology and other disciplines related to ancient writing cultures;
- **plan a syllabus for delivering digital competences** to trainees in the field of ancient writing cultures (with the help of experts where necessary).

### Abstract

The **ENCODE** open online course 'Digital tools for the research and study of ancient writing cultures' is designed to introduce teaching staff, GLAM professionals, and graduates to ancient writing cultures and digital studies. It consists of four units: Digital Greek-Latin Epigraphy, Digital Papyrology, Multilingual-Multicultural Digital Infrastructures & How to create LOD.

**Comment by VickyGarnett** [comment]
Hi @fosco13 - great to see this resource going onto Campus!  I've added all those people to the system now, so you can crack on with drafting this up.  If you would like a quick call to demo how to use the CMS then we can set that up.  Otherwise, you can also find a step-by-step guide in our documentation here: https://campus.dariah.eu/docs/using-the-content-management-system - you will also find the link to the CMS there.  Thanks!  V

**Comment by fosco13** [comment]
Thanks @VickyGarnett! I'll take a look at the guide this week, but I think I'll manage 👍 
If not, I'll let you know and we can indeed schedule a quick call...

All best,
Tom

**Comment by VickyGarnett** [comment]
resource published, closing issue
