### ISSUE TITLE
change the behavior of curriculum overview

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#120]
### Bug report

At the moment, clicking on a resource in "this curriculum contains" overview (https://dariah-campus-six.vercel.app/curriculum/the-parthenos-complete-guide-to-research-infrastructures)  takes us directly to the resource in question. I would like to change this:

- please rename "This curriculum contains" to "Curriculum overview"
- make the overview stick with the text (at the moment if you scroll down to the last resource on the overview page, you will lose the overview links)
- have each link scroll to the resource title on overview page (instead of opening the resource page directly).

If possible, it would also be nice to highlight the links in the overview as the users scrolls down the page and reaches individual titles and abstracts —  to mimic the behavior of the table of contents.

**Comment by stefanprobst** [comment]
> make the overview stick with the text (at the moment if you scroll down to the last resource on the overview page, you will lose the overview links)

that's just how css `position: sticky` works - when you scroll to the end, the `footer` will push the rest of the page up, including the sidebar and its sticky content.

**Comment by ttasovac** [comment]
@stefanprobst I've merged #123. would it also be possible to

> highlight the links in the overview as the users scrolls down the page and reaches individual titles and abstracts — to mimic the behavior of the table of contents. 

(this will be especially useful when we have 20 courses in a curriculum, like for ELEXIS)

**Comment by stefanprobst** [comment]
> highlight the links in the overview as the users scrolls down the page and reaches individual titles and abstracts — to mimic the behavior of the table of contents.

true, sorry forgot about that - yes let's add this
