### ISSUE TITLE
cms: logo missing

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#139]
### Bug report

<img width="822" alt="Снимок экрана 2021-09-01 в 14 01 07" src="https://user-images.githubusercontent.com/5304839/131668148-08a84414-f890-4703-a61a-3b4c089eb63a.png">

This is of course for after Stefan's :be

**Comment by stefanprobst** [comment]
![Screenshot_20210901_142052](https://user-images.githubusercontent.com/20753323/131670215-a81f2476-4a2f-4bec-844c-d155beef6d56.png)

this is what is see by default. could you clarify how to reproduce this? thx

**Comment by ttasovac** [comment]
It's a Safari issue again. (I just checked and "changes saved" show up in Chrome and Firefox). 

The problem is with:

    <div class="css-epy1pj-BackStatus-BackStatusUnchanged-badge-textBadge-textBadgeSuccess evqrzhe14">Changes saved</div>

when i remove that class name, I can see the text without some of the styling:

<img width="673" alt="Снимок экрана 2021-09-01 в 14 41 37" src="https://user-images.githubusercontent.com/5304839/131672972-8bfda8d4-ab8b-402e-a6c9-3f1320a825a2.png">

more specifically, i think the problem is in `display:inline-block` because when I change that to `inline-flex` for instance, I get this:

<img width="576" alt="Снимок экрана 2021-09-01 в 14 53 03" src="https://user-images.githubusercontent.com/5304839/131674482-bbff4b43-f48c-45a5-bdf2-a7e3abdbe63b.png">

which is almost right —  although it has that weird little square...

I don't know how to fix this at all...

**Comment by stefanprobst** [comment]
looks like this is https://github.com/netlify/netlify-cms/issues/5411

**Comment by ttasovac** [comment]
alles klar! let's see if they come up with an official fix. 

thanks stefan. now off to the beach! :) 
--
Belgrade Center for Digital Humanities
http://humanistika.org

**Comment by ttasovac** [comment]
stefan made a pull request about this https://github.com/netlify/netlify-cms/pull/5776 —  let's see if gets reviewed soon
