### ISSUE TITLE
running DC without Algolia credentials

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#14]
Hi Stefan.

Currently, we have to have ALGOLIA API keys etc. in order to run D-C locally. I've shared the keys with my DARIAH colleagues, but I think we need a different approach for external contributors to D-C who want to run the server locally while working on their training materials.

I was wondering if we could do something about it. Could we for instance refactor the code to NOT use Algolia if there are no Algolia credentials on the systems and in those cases reuse our old JS code for search, i.e. essentially avoiding Algolia altogether?

Or is .env.production something we can and should share with everybody?

I'm open to other suggestions of course.

All best,
Toma

**Comment by stefanprobst** [comment]
Easiest option would be to push `.env.development` (i.e. remove from `.gitignore`) -- anything in there is public anyway. This would mean everyone could run the development build locally (but not `gatsby build` which will actually update the algolia index, and therefore needs the api key from `.env.production`)

**Comment by ttasovac** [comment]
agreed
