### ISSUE TITLE
TRIPLE training session : The ORE platform

### ISSUE THREAD

**Issue by EmilieHN** [DARIAH-ERIC/dariah-campus#141]
### Title of the resource

The ORE platform

### Resource type

Captured Event

### Authors, editors and contributors

Francesca Di Donato,Emma Lazzeri, Ilaria Fava

### Topics (keywords)

Open Science, Open Research Europe platform, publishing platforms, Horizon Europe, Scientific Communication, Open Peer Review

### Learning outcomes

The new platform will make it easy for Horizon 2020 beneficiaries to comply with the EU Open Access terms of funding at no cost to them. It offers to the researchers a free publishing venue to share their results and insights rapidly and facilitate open and constructive research discussions. Even if the EU-funded project has ended, publications stemming from the project can be submitted. Each publication must have at least one author who has been, or still is, a recipient of an EU grant.

### Abstract

🏠 Venue: Virtual event via Zoom
📋 Slides: [https://doi.org/10.5281/zenodo.4707975]
📽 Recording:[https://youtu.be/_3jpFxtKIME]

A webinar about the new Open Access Publishing Platform Open Research Europe (ORE) – what it is and how it works.

On the Horizon 2020 website of the EU the service is described as follows: “ORE is a new, free, open access, peer-review publishing platform for the publication of results stemming from EU-funded research.  It publishes articles categorised in six subject areas: Natural Sciences, Engineering and Technology, Medical Sciences, Agricultural Sciences, Social Sciences, Humanities and Arts. For each of the six categories, there are different kind of types of publications, ranging from research articles, to brief reports, essays, data, method articles, etc.

The ORE website currently contains all necessary guidance (policies, publishing process, Scientific Advisory Board and FAQ) as well as information and instructions for the submission workflow. The platform is now open for submissions but the full range of functionalities (search, grouping per areas and thematic gateways) will become active only at the time of the formal launch, in March 2021.”

**Comment by VickyGarnett** [comment]
Hi Emilie - This isn't necessarily now, but before publishing this resource, please review the Learning Outcomes so that they more closely match the style shown on this webpage: https://assessment.provost.wisc.edu/student-learning-outcomes/writing-student-learning-outcomes/.  They should be listed in bullet points, all starting with a verb.  Thanks  - V :)

**Comment by LottieProvost** [comment]
Hi Vicky, I'll take care of it, thanks for pointing it out !

**Comment by VickyGarnett** [comment]
Hi Lottie - I'm just checking, have you created this resource on the CMS yet?  Have you sent it through to 'In Review'?  I don't seem to have it in my Pull Requests, so I wanted to check.  Does it have the same name?  Thanks - V :)

**Comment by LottieProvost** [comment]
Hi Vicky, I created another resource called The Open Access Publishing platform ORE and it has been in review since October 20th if I am not mistaken. This issue can be closed/deleted :-) thanks you !

**Comment by VickyGarnett** [comment]
Hi Lottie - I'm not seeing any of the Pull Requests that you have prepared for TRIPLE here on GitHub.  Could you just double-check that the resources have been sent to 'In Review' in your workflow?  Thanks!  - V :)

**Comment by VickyGarnett** [comment]
Apologies - I AM seeing PRs from you, but I'm not seeing 'The Open Access Publishing Platform ORE'.  I think this is the only one you need to double check here :) - V

**Comment by LottieProvost** [comment]
Hi Vicky,

Yes, unless I'm mistaken the resources have been sent to "In Review".

Here is a screenshot of my workflow, the one on The Open Access Publishing
Platform ORE is at the bottom.

Let me know if I got something wrong. :-)

Best,

Lottie
[image: Capture d’écran 2021-11-04 à 15.58.13.png]

Le jeu. 4 nov. 2021 à 15:36, VickyGarnett ***@***.***> a
écrit :

**Comment by VickyGarnett** [comment]
Hi Lottie - I'm afraid I'm not seeing your screengrab.  Perhaps you could email it to me directly?  Thanks!  - V :)

**Comment by LottieProvost** [comment]
Hi Vicky,

please find attached the screenshot from my workflow. Hope this helps :)

Best,

Lottie

Le jeu. 4 nov. 2021 à 21:08, VickyGarnett ***@***.***> a
écrit :

**Comment by VickyGarnett** [comment]
Still no screenshot.  Can you email it to my DARIAH account please?  We might have better luck that way :) - V
