### ISSUE TITLE
adjust schema.org `@type` on resource pages

### ISSUE THREAD

**Issue by stefanprobst** [DARIAH-ERIC/dariah-campus#142]
### Bug report

we currently add schema.org metadata to resource pages with `@type: LearningResource`. however, judging by [this list](https://developers.google.com/search/docs/advanced/structured-data/search-gallery) (and the results [here](https://search.google.com/test/rich-results)) this is a type which is not recognized by google search. we might want to pick one from the list above.

**Comment by ttasovac** [comment]
hey @stefanprobst sorry i missed this.

let's go for "Course"

I wonder though, whether we should use "Video" for our resources that are classified as videos. What do you think?

**Comment by stefanprobst** [comment]
> I wonder though, whether we should use "Video" for our resources that are classified as videos. What do you think?

good point - let's try it!

**Comment by stefanprobst** [comment]
on second thought - `Video` is a bit trickier, because we don't have the video url in the resource metadata, so we would need to extract it from the `VideoCard` attribute

**Comment by ttasovac** [comment]
if it's too much trouble, don't worry about it.

**Comment by stefanprobst** [comment]
closed by #206
