### ISSUE TITLE
[new resource]: DARIAH-DE Publikator Video Tutorial

### ISSUE THREAD

**Issue by melina-jander** [DARIAH-ERIC/dariah-campus#158]
### Title of the resource

DARIAH-DE Publikator: Video Tutorial 

### Resource type

External Resource

### Authors, editors and contributors

DARIAH-DE

### Topics (keywords)

repository, publication, FAIR, data management

### Learning outcomes

Learners will: 

- get to know the DARIAH-DE Repository and its publication tool, the DARIAH-DE Publikator;
- receive a step-by-step guide on how to upload data(-sets) into the Repository and how to index them with meta data;
- be encourage to use the tool for their own data management and publication. 

### Abstract

The video tutorial, which is embedded into the DHd / TextGrid Youtube channel, provides a step-by-step guide through the DARIAH-DE Publiaktor, a tool that enables its users to upload data(-sets) into the DARIAH-DE Reposiotry and index them with meta data. The tool is part of the larger DARIAH-DE Data Federation Architecture, aiming to support the FAIRification of research data with regards to the research data life cycle. 

The video provides both information about DARIAH-DE and an easy to follow guide through the tool. It is about 20 mins long. 
The language is German.

**Comment by VickyGarnett** [comment]
Hi Melina,

Thanks for sending this through.  Is this something entirely new, or this an addition to the Publikator Tutorial?  If so, I wonder if maybe it might be neater if you edited the Publikator Tutorial external resource page that is already published to Campus, and add this video to it?  https://campus.dariah.eu/resource/posts/dariah-de-publikator-tutorial

Thanks!

V

**Comment by melina-jander** [comment]
Hi Vicky, 

Thanks for the quick reply. I agree that it might be better to add the video to the already published entry. What's important to us, though, is that we can clearly state that the format of this source is a video - but I can alter the entry accordingly, right? 

Thanks you
Melina

**Comment by VickyGarnett** [comment]
You should be able to change the resource type to video.  But I want to be clear - is this video showing exactly the same information as the module that was published earlier in the year?  If so, then I think we should proceed with putting this together on the original Publikator resource.  This will need some re-wording, but we can discuss that once you've submitted it.

However, if this is a video that shows completely new information that isn't covered in the original tutorial, then we can publish this as a separate resource, and look at putting them together in a broader 'DARIAH-DE Tools Curriculum', which might also incorporate the Repository tutorial.  

Let me know which way you'd like to go with it. :)

V

**Comment by melina-jander** [comment]
No, it's not completely new information. It's a visualisation of the information in the written source, so I think it would be best to put them together and make it clear that there are two types of tutorial for the Publikator but with the same information. 

Thanks,
Melina

**Comment by VickyGarnett** [comment]
Hi Melina - I've had a chat with Toma, and he's in favour of going with the original plan of having them as 2 separate resources, but we need to be clear that they are related, and add a link towards the top of both resources to indicate this.

**Comment by melina-jander** [comment]
Hi Vicky, 

Okay, thank you. I will then draft a first version in the beginning of next week - unless you have other suggestions or wishes on how to proceed?
