### ISSUE TITLE
[new resource]: FAIR Data in Social Sciences and Humanities

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#163]
### Title of the resource

FAIR Data in Social Sciences and Humanities

### Resource type

External Resource

### Authors, editors and contributors

Elena Giglia, Arnaud Gingold, Francesca Di Donato, Lottie Provost, Iraklis Katsaloulis

### Topics (keywords)

FAIR principles, Data management, Digital archives, Training and Education, Humanities

### Abstract

This training event from the TRIPLE Project was devoted specifically to FAIR Data in SSH, and it provided answers to the following questions, among others: How is research data in SSH defined? Why are FAIR principles important for the management of research data in SSH? How can the FAIR principles be implemented in SSH?

**Comment by VickyGarnett** [comment]
Hi Lottie - could you include some Learning Outcomes to this resource?  This website is very useful in how to format and write learning outcomes for this sort of thing: https://assessment.provost.wisc.edu/student-learning-outcomes/writing-student-learning-outcomes/

Thanks  - V :)

**Comment by LottieProvost** [comment]
Dear Vicky,

Thanks for your email.

I saw that the learning outcomes were not mandatory when filling out the
new resource submission so I skipped them to gain some time.
However I do remember during our call that you stressed the importance of
the learning outcomes and that's why I was thinking of writing them
properly once the new resource is accepted.
I've submitted 4 new resources this morning and skipped the learning
outcomes in all of them...

Should I edit all requests or is it ok to do it later on?

Thanks a lot in advance!

Kind regards,

Lottie





Il lun 27 set 2021, 12:35 VickyGarnett ***@***.***> ha
scritto:

**Comment by VickyGarnett** [comment]
Hi Lottie - thanks for getting back so quickly.  As long as you are thinking about the learning outcomes and will include them in the main resource, that's fine :) - V

**Comment by LottieProvost** [comment]
Yes, sure I will!

I will have more time in a few days and I just wanted to create the new
resources quickly.

I promise I'll insert the mearning outcomes in the structured way you
showed us :-)

Have a lovely day,

Lottie

Il lun 27 set 2021, 12:45 VickyGarnett ***@***.***> ha
scritto:

**Comment by VickyGarnett** [comment]
Hi Lottie - to tidy up both our GitHub 'Issues' tabs, I'm going to close this issue as you've created the resource now.  I'll be doing this for all the other issues that have associated Pull Requests.  Thanks - V :)
