### ISSUE TITLE
[new resource]: EOSC State of the Art and Perspectives

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#164]
### Title of the resource

EOSC State of the Art and Perspectives

### Resource type

External Resource

### Authors, editors and contributors

Suzanne Dumouchel, Erzsébet Tóth-Czifra, Francesca Di Donato, Lottie Provost

### Topics (keywords)

Open Science, Training and Education, EOSC

### Abstract

This training event from the TRIPLE Project was devoted specifically to the European Open Science Cloud (EOSC), and it provided answers to the following questions, among others: What is the state of the art of the EOSC development? How the EOSC governance is changing? What are the next steps for the EOSC implementation?

**Comment by VickyGarnett** [comment]
Hi Lottie - as with the previous submission, could you include some Learning Outcomes?  Thanks :)

**Comment by LottieProvost** [comment]
Dear Vicky, I have created a draft resource for this training session. I have included learning outcomes, could you please tell me if these are fine by you ? Thanks a lot :)

**Comment by VickyGarnett** [comment]
Resource created and Pull Request received, so closing this issue now :)
