### ISSUE TITLE
[new resource]: EOSC Onboarding

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#165]
### Title of the resource

EOSC Onboarding

### Resource type

External Resource

### Authors, editors and contributors

Joshua Tetteh Ocansey, Carsten Thiel, Luca De Santis, Francesca Di Donato

### Topics (keywords)

Open Science, Training and Education, EOSC

### Abstract

This training event from the TRIPLE Project was designed specifically to provide assistance to service providers to share services via EOSC with the EOSC Portal as well as to introduce some of the benefits of the EOSC Portal. The training session aimed at explaining the minimum criteria to become a provider and requirements to onboard services into the EOSC Portal; describing in detail the EOSC onboarding process; and gathering requirements from the TRIPLE project in order to take them into account for the next iteration of the Portal development.

**Comment by VickyGarnett** [comment]
Resource created and Pull request received, closing issue :)
