### ISSUE TITLE
full metadata display

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#17]

**Comment by stefanprobst** [comment]
we now display all remaining metadata at the bottom of a resource. anything missing?

**Comment by ttasovac** [comment]
Thanks —  it looks good.

I would actually prefer to display ALL metadata, not just the remaining fields. There will be some duplication of content, but I think that's fine. 

By the way, how does the Last modified field work? At the moment every resource seems to have the last modified date of December 11th, which seems to suggest that ALL resources get the last update date changed on ANY update on the website, which shouldn't really be the case. We would want this value to change only if a particular resource was actually changed.

**Comment by stefanprobst** [comment]
> I would actually prefer to display ALL metadata, not just the remaining fields.

:+1:

> how does the Last modified field work?

it looks up the `mtime` (modified time) file attribute -- however, i guess because netlify always pulls the whole repo, the file attribute will be set to whenever it builds (?). hmm, not sure how automatically setting `lastModified` could work then...

**Comment by stefanprobst** [comment]
just tried and `dateModified` works correctly locally

**Comment by stefanprobst** [comment]
we now display all fields (except title). `lastModified` should work correctly as well (we now get the date from the git commit)

**Comment by ttasovac** [comment]
added title in https://github.com/DARIAH-ERIC/dariah-campus/commit/89407391f25a730b6295106a1b964a0e1a293a6d
