### ISSUE TITLE
[new resource]: EOSC Architecture

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#171]
### Title of the resource

EOSC Architecture

### Resource type

External Resource

### Authors, editors and contributors

Ville Tenhunen, Yin Chen, Lottie Provost, Francesca Di Donato

### Topics (keywords)

Open Science, Training and Education, EOSC

### Abstract

This training event from the TRIPLE Project was devoted specifically to the EOSC Architecture, and provided answers on the following topics, among others: Overview of the EOSC Architecture principles; Main components of the EOSC Architecture; Interoperability in the EOSC Architecture; Main documents, projects and further development.

**Comment by VickyGarnett** [comment]
Resource created and Pull Request received so closing issue :)
