### ISSUE TITLE
[new resource]: Dublin in the Archives: Digital collections exploring the city and county

### ISSUE THREAD

**Issue by DEThorpeDRI** [DARIAH-ERIC/dariah-campus#177]
### Title of the resource

Dublin in the Archives: Digital collections exploring the city and county

### Resource type

External Resource

### Authors, editors and contributors

Brendan Teeling, Emma Clarke, Karen De Lacey, Joe Lee, James Louis Smith

### Topics (keywords)

History, Community Archives, Ireland, Digital archiving, Digital preservation, Ghost signs, Community films, Dublin Ports

### Abstract

This recording is of ‘Dublin in the Archives: Digital collections exploring the city and county’, a webinar hosted by the Digital Repository of Ireland as part of the Culture Night 2021 programme of events.

Digital archives are bursting with collections relating to Dublin’s past and present. They trace the boundaries and geography of the city and the social, cultural, and business life of Dubliners through the centuries. This webinar brings together the content creators of these exceptional collections as well as the historians, geographers, and curators of digitised records to showcase Dublin’s digital cultural heritage.

The event is chaired by Deputy City Librarian at Dublin City Libraries and Archives (DCLA), Brendan Teeling. Speakers include:

- Emma Clarke, Founder of Dublin Ghost Signs
- Karen De Lacey, County Archivist at Fingal County Council
- Joe Lee, Independent Film and Video Maker
- Dr James Louis Smith, Postdoctoral Fellow at University College Cork for the Ports, Past and Present project

**Comment by VickyGarnett** [comment]
Hi Debs - All those names are in the CMS ready for you to use, so you can continue to create this resource now.  Thanks - V :)
