### ISSUE TITLE
[new resource]: Performing, Promoting and Preserving Ireland’s Intangible Cultural Heritage

### ISSUE THREAD

**Issue by DEThorpeDRI** [DARIAH-ERIC/dariah-campus#178]
### Title of the resource

Performing, Promoting and Preserving Ireland’s Intangible Cultural Heritage

### Resource type

External Resource

### Authors, editors and contributors

Manchán Magan, Claire Fennell, Emmett Gill, Michael Houlihan, Seán Mac Philbín, Natalie Harrower, Sinéad O’Hara

### Topics (keywords)

Digital preservation; Intangible cultural heritage; Wells; Traditional music; Musical instruments; Musical performances; Drama; Digital heritage

### Abstract

This recording is of 'Performing, Promoting and Preserving Ireland’s Intangible Cultural Heritage'. This was a live online event co-organised by the Department of Tourism, Culture, Arts, Gaeltacht, Sport and Media and the Digital Repository of Ireland on 19 August 2021 at 19.00.

Original event description:

What is intangible cultural heritage? Why is it important? How can it be protected? How can digital records of these practices help to pass them down to future generations?

In December 2015, Ireland ratified the UNESCO 2003 Convention for the Safeguarding of the Intangible Cultural Heritage. Intangible cultural heritage ‘refers to the practices, representations, expressions, knowledge, skills – as well as the instruments, objects, artefacts and cultural spaces associated therewith – that communities, groups and, in some cases, individuals recognize as part of their cultural heritage’. The National Inventory for Intangible Cultural Heritage has been established to protect, promote and celebrate Irish living cultural heritage practices, customs, crafts and traditions.

Join Manchán Magan online during Heritage Week 2021 for a lively evening of performance, exploration, and discussion on the theme of intangible cultural heritage. The Department will speak about the development of the National Inventory. Practitioners and performers from three performing arts will give insights into their practices and why they are important. The Digital Repository of Ireland will ask us to think about how the preservation of digital records can help to pass practices like these down to future generations. Manchán will then open the floor to questions, as you are invited to join with us in recognising and experiencing this important element of Ireland’s cultural heritage.

Panellists:

Claire Fennell and Emmett Gill, Na Piobairí Uilleann

Claire Fennell is a multi- instrumentalist. She plays uilleann pipes, flute and tin whistle and has many All-Ireland titles on these instruments. Claire has a Bachelor of Music from CIT Cork School of Music, a Masters’ degree in Music Education in the University of Limerick and is now a qualified Music Secondary School Teacher.

Emmett Gill is an uilleann piper and Archivist with Na Píobairí Uilleann (NPU). Born in London into a musical Irish family, Emmett has played the pipes from an early age. He regularly performs and teaches the uilleann pipes.

Michael Houlihan, The Holy Wells of County Clare

Micheal Houlihan has produced books on Holy Wells, Sacred Trees and Clare’s mythical landscape. Currently he is completing work with Clare County Council in identifying and recording all of Clare’s 240 Holy Wells.

Seán Mac Philbín and the Mummers of Fingal

Seán MacPhilibín is Dublin City born, founded the Fingal Mummers in 1984, and has over 40 years involvement with intangible cultural heritage in Fingal. The evening’s performance will illustrate key elements of a Fingal Mummers performance, including; masking; performing the Mummers Play; playing music; and dancing.

These practitioners will be accompanied by Sinéad O’Hara of the Department of Tourism, Culture, Arts, Gaeltacht, Sport and Media and Natalie Harrower, Director of the Digital Repository of Ireland.

**Comment by VickyGarnett** [comment]
Hi Debs - the names for this contribution are all in the CMS so you can continue to create the resource now.  Thanks - V :)
