### ISSUE TITLE
[new resource]: Engaging Communities with Archives: Video as a tool for activism, advocacy, and archival work

### ISSUE THREAD

**Issue by DEThorpeDRI** [DARIAH-ERIC/dariah-campus#179]
### Title of the resource

Engaging Communities with Archives: Video as a tool for activism, advocacy, and archival work

### Resource type

External Resource

### Authors, editors and contributors

Laura Aguiar; Lynsey Gillespie; Yvonne Ng; Elizabeth (Liz) Miller

### Topics (keywords)

Community Archives; Community Engagement; Video recording; Activism; Human rights; advocacy; Digital preservation; Digital archiving; Storytelling

### Abstract

This recording is of ‘Engaging Communities with Archives: Video as a tool for activism, advocacy, and archival work’, a collaborative event hosted by the Digital Repository of Ireland (DRI) and the Public Record Office of Northern Ireland (PRONI) on 7 Sept 2021.

The webinar focuses on participatory projects that aim to train or support community groups in using video to tell personal stories, bring about social change, or archive and preserve activism and advocacy work. The aim of the webinar was to open up an international conversation about how organisations can collaborate with care with community groups to empower people with the knowledge and skills to create and preserve their own stories.

Speakers include:

• Lynsey Gillespie, Archivist at PRONI: Lynsey is an archivist at PRONI and the curator for Making the Future, a cross-border cultural programme that aims to empower people to use museum collections and archives to explore the past and create a powerful vision for future change. Lynsey speaks about this project, focussing particularly on the ‘Every Day is a School Day’ initiative, a series of 10 short films created by a group of participants with varying degrees of sight loss as part of Making the Future’s 100 Shared Stories programme.
• Yvonne Ng, Archives Program Manager, WITNESS: Yvonne is an audiovisual archivist and manages the archives program at WITNESS, where she trains and supports partners on collecting, managing, and preserving video documentation for human rights evidence and advocacy. Yvonne speaks about community-based approaches to archives and how WITNESS supports human rights activists to create their own archives through training and resources.
• Elizabeth (Liz) Miller, Professor in Communication Studies, Concordia University: Liz is a documentary maker and professor interested in new approaches to community collaborations and to documentary making as a way to connect personal stories to larger social concerns. Liz speaks about Mapping Memories, a participatory media initiative that offered over a hundred young individuals the opportunity to recount their stories of refugee experiences on their own terms.

The event is chaired by Dr Laura Aguiar, Community Engagement Officer & Creative Producer at PRONI.

**Comment by VickyGarnett** [comment]
Hi Debs - as you've now created the resource and we've received the PR, I'm going to close this issue now.  Thanks!  V :)
