### ISSUE TITLE
[new resource]: Collecting in a Crisis: Rapid Response Web and Social Media Archiving

### ISSUE THREAD

**Issue by DEThorpeDRI** [DARIAH-ERIC/dariah-campus#180]
### Title of the resource

Collecting in a Crisis: Rapid Response Web and Social Media Archiving

### Resource type

External Resource

### Authors, editors and contributors

Nicola Bingham, Valerie Love

### Topics (keywords)

Rapid Response, COVID-19, Social Media Archiving, Web Archiving, Meme Culture

### Abstract

This video recording is of a collaborative webinar, organised by the Digital Repository of Ireland and National Archives, Ireland, as part of a public lecture series on digital archiving. Digital archivists have played an essential role on the front lines of the effort to document the COVID-19 pandemic. This webinar explores their rapid response web and social media archiving initiatives.

Speakers include:

Nicola Bingham: Nicola is the Lead Curator of Web Archiving at the British Library in the Department of Collections.

Valerie Love: Valerie is the Senior Digital Archivist at the Alexander Turnbull Library, New Zealand.

**Comment by VickyGarnett** [comment]
Hi Debs - all good to add this resource,  Please remember that the abstracts need to give brief info of the content of the webinar rather than the details - Thanks!  V :)
