### ISSUE TITLE
[new resource]: Archival Activism: Community-Centred Approaches to Archives

### ISSUE THREAD

**Issue by DEThorpeDRI** [DARIAH-ERIC/dariah-campus#181]
### Title of the resource

Archival Activism: Community-Centred Approaches to Archives

### Resource type

External Resource

### Authors, editors and contributors

Sharon Webb, Boni Odoemene, Zakiya Collier

### Topics (keywords)

Community archives, Black Irish Community, Instagram collections

### Abstract

This video recording is of a collaborative webinar, organised by the Digital Repository of Ireland and National Archives, Ireland, as part of a public lecture series on digital archiving. The webinar highlights the memory work of community archivists who are building freely accessible online collections documenting the stories of their communities and making important decisions about how these stories should be collected, organised, and shared. The webinar opens up a conversation about how national memory institutions can offer their digital preservation skills and profession-based knowledge to support community-based archival initiatives and form equitable partnerships.

Speakers include:

Dr Sharon Webb: Sharon is a Lecturer in Digital Humanities at the University of Sussex, History Department, and a member of the Sussex Humanities Lab. Sharon’s research interests include community archives and identity, with a special interest in LGBTQ+ archives, feminist and BAME archives, social network analysis (method and theory), and research data management.

Boni Odoemene: Boni is one is one of the co-founders of Black and Irish, a social media community that aims to highlight and celebrate the identity of Black Irish people by spreading awareness around the world of the experiences, struggles and successes of the Black Irish community.

Zakiya Collier: Zakiya is the Digital Archivist at the Schomburg Center for Research in Black Culture where she uses web archiving tools to expand the nature of archival collections to reflect 21st-century Black life and experiences.

**Comment by VickyGarnett** [comment]
Names in CMS - please continue to add resource.  Thanks - V :)
