### ISSUE TITLE
[new resource]: The Power of a Photograph: Collecting and Digital Preservation in Times of Social Change

### ISSUE THREAD

**Issue by DEThorpeDRI** [DARIAH-ERIC/dariah-campus#187]
### Title of the resource

The Power of a Photograph: Collecting and Digital Preservation in Times of Social Change

### Resource type

External Resource

### Authors, editors and contributors

Della Keating, Joanna Finegan

### Topics (keywords)

COVID-19, Photograph collections, Rapid Response, Yes Equality, Marriage Equality, Referendum

### Abstract

This video recording is of a presentation delivered as part of a collaborative webinar, organised by the Digital Repository of Ireland and National Archives, Ireland, as part of a public lecture series on digital archiving. In this presentation, Della Keating and Joanna Finegan of the National Library of Ireland (NLI) ask ‘what will we know about the present in 100 years’ time if an important aspect of Irish culture is not preserved now?’ They highlight the power of photographs for recording social change and briefly discuss some of the challenges and issues around their long-term preservation, particularly in the digital world. They also discuss the work of the NLI in preserving Ireland’s contemporary heritage in digital form, highlighting the Yes Equality Visual Digital Archive of photographs commissioned for the marriage equality campaign as well as the NLI Selective Web Archive which is a rich resource for visual content.

Speakers:

Della Keating, Assistant Keeper I – Digital Collecting, NLI
Joanna Finegan, Assistant Keeper I – Digital Collecting, NLI

**Comment by VickyGarnett** [comment]
Thanks Debs! Please continue to add resource in the CMS.  V :)
