### ISSUE TITLE
[new resource]: CLARIN Café on the Rights of Data Subjects in Language Resources

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#209]
### Title of the resource

CLARIN Café on the Rights of Data Subjects in Language Resources

### Resource type

External Resource

### Authors, editors and contributors

Esther Hoorn, Paweł Kamocki , Aleksei Kelli, Francesca Frontini, Vanessa Hannesschläger

### Topics (keywords)

Training and Education, Open Science, Research Infrastructures, Data Management, DH, Scholarly Practice

### Learning outcomes

After watching this video, you should:

- Understand what rights the GDPR grants to data subjects.

- Understand if these rights are limited when personal data is processed for the purpose of language research.

- Understand how to handle data subjects’ requests related to the exercise of their rights.

- Understand who is responsible for handling data subjects’ requests related to the exercise of their rights.

### Abstract

This training event was a joint collaboration between CLARIN and the TRIPLE project. It was devoted specifically to the rights of data subjects in the GDPR and provided information on the following topics: The rights granted to data subjects by the GDPR; The limitations of these rights when personal data is processed for the purposes of language research; The handling of data subjects’ requests related to the exercise of their rights.

**Comment by VickyGarnett** [comment]
Hi Lottie - Those people have now been added, so you should be able to proceed to creating the new resource.  Thanks :) - V

**Comment by LottieProvost** [comment]
Hi Vicky,

thanks for the confirmation!

I was wondering if I should wait to have 5 resources ready as drafts before
sending them for publication (to be able to have them under a common TRIPLE
source).

Thanks in advance.

Lottie

Le mer. 6 oct. 2021 à 18:27, VickyGarnett ***@***.***> a
écrit :

**Comment by VickyGarnett** [comment]
Hi Lottie - it could take a while to get the 'Source' channel set up, and we find organisations get more of a hit if they publish resources separately in any case, so I think it would be better if you didn't save them all up.  We can retrospectively add the 'Source' channel at a later stage - V :)

**Comment by LottieProvost** [comment]
Hi Vicky,

thank you for your email. I have just sent 5 resources to review, please
let me know if anything needs to be changed. :)

I was wondering: what are the next steps to create a TRIPLE source channel
and will the EOSC tag  be added in the near future ?

Thanks in advance,

All the best,

Lottie

Le mar. 12 oct. 2021 à 11:42, VickyGarnett ***@***.***> a
écrit :

**Comment by VickyGarnett** [comment]
Hi Lottie - Thanks for this.  We've had a huge rush of resources sent in to us since we launched the CMS, so I'm making my way through them all slowly but surely!  Regarding the EOSC tag - that can be added retrospectively, so please don't let that hold you up in completing any resources and sending them through.  Re the Source Channel, that's something I'll have to discuss with Toma during our next D-C editorial meeting, so it may take a little while to sort that one out.  But as I said, it can be added retrospectively, so it shouldn't slow down publication.  I hope that helps!  - V :)

**Comment by LottieProvost** [comment]
Thanks for your quick reply Vicky!

I hope the resources I sent are correct and don't need modifying.

Talk to you soon then!

Kind regards,

Lottie

Le jeu. 14 oct. 2021 à 12:16, VickyGarnett ***@***.***> a
écrit :

**Comment by VickyGarnett** [comment]
EOSC tag now added, so please continue to add the resource :)  Thanks!  V
