### ISSUE TITLE
[new resource]: Use of ICT for Community Building Actions Towards the Reactivation of Urban Heritagescapes in South European Cities

### ISSUE THREAD

**Issue by Chopium** [DARIAH-ERIC/dariah-campus#235]
### Title of the resource

Use of ICT for Community Building Actions Towards the Reactivation of Urban Heritagescapes in South European Cities

### Resource type

Captured Event

### Authors, editors and contributors

Georgios Artopoulos, Colter Wehmeier, Carlos Smaniotto, Gaia Redaelli, Fabio Montagnino, Jürgen F. Weishäupl

### Topics (keywords)

Augmented Reality, Community Building, Smart Cities, Built Heritage, Participatory Design, eHeritage

### Learning outcomes

>Learn how community-building processes are structured to entice participation and tap on data for insights from local stakeholders. Being introduced to a discussion about the various challenges of co-creation regarding the ways user input can be integrated into design /planning proposals of future architectural interventions in neglected heritage sites of historic cities with the objective to inform local authorities and key stakeholders, responsible for the development of urban infrastructure and the city.

>Being informed about new technical solutions for rapid 3D documentation and reconstruction of urban heritage sites; the use of these 3D reconstructions of sites through reality capture methods in co-creation processes; and, reflecting on the capacities of mobile apps (using augmented reality) to facilitate the visualization of design scenarios in a form that is accessible by non-experts, as well as to provide a platform for dialogue between all stakeholders of urban heritage.

>Learn about the state-of-the-art theories and approaches to sustainable heritage and listen to reflections from experienced architects, academics, and urban thinkers, on critical issues of urban gentrification, place-making, the pressures that historic urban neighbourhoods in cities of the European South are experiencing from current design and planning approaches that ignore the recommendations of international bodies such as UN Habitat; and being exposed to a discussion about the role of ICT (specifically, mobile apps) in enabling contemporary inhabitants to grow a sense of belonging for communal heritage spaces.

### Abstract

The DARIAH Working Group on “Digital Practices for the Study of Urban Heritage” organised a public space co-creation workshop with the title “Everyday experiences and heritage in south European cities: Digital tools and practices” that was held at Cantieri Culturali della Zisa, Palermo, 25-30 July 2021.

Challenged by urbanization, economy, gentrification, migration, and climate change the experience of historical spaces and buildings is fragmented, thus mirroring the disconnected perception of urban societies. The workshop studied how urban heritage and the abundance of culturally valuable structures in specific historic cities across Europe which are challenged by current pressing conditions can contribute to reflective processes and the creation of legible, inclusive, accessible, resilient and enjoyable cities. Data collection and co-creation was facilitated by the use of citizen volunteered geolocation software (readily available to the participants by the organisers), such as DEUSTO Tech DARIAH app and WIKAR AR app (https://wikar.co/).

**Comment by VickyGarnett** [comment]
Hi!  Great to see this proposed, I think it'll be a great addition to Campus!  I'll add those names and then let you know when it's ready to go.  The Captured Events can be a little tricky to navigate though, so do give me a shout if you are confused about anything. - Thanks - V :)

**Comment by VickyGarnett** [comment]
Hi again.  The names of the authors are now in the system, so you can start drafting up the resource as per the guidelines we've put together here: https://campus.dariah.eu/docs/using-the-content-management-system

Just a couple of notes - the learning outcomes are a little long,.  You should aim for one short sentence per learning outcomes, starting with a verb to complete the sentence "After completing this learning resource you should.....".   

Also - I haven't added all of the requested tags as we don't have anything else currently in Campus that would fit those tags.  We try to keep tags as general as we can so we don't end up with a load of very specific tags that only relate to one resource.

Give me a shout if you need any help, or clarification of anything in the guidelines!  Looking forward to seeing this come through :)  V

**Comment by Chopium** [comment]
> The DARIAH Working Group on “Digital Practices for the Study of Urban Heritage” organised a public space co-creation workshop with the title “Everyday experiences and heritage in south European cities: Digital tools and practices” that was held at Cantieri Culturali della Zisa, Palermo, 25-30 July 2021.

After falling off on this, I started developing the resource. I am having problems trying to upload media to the site. Are large files not supported? Should I be hosting elsewhere and embedding things like long videos?

This is the content we're dealing with. I have been unable to upload any files so far, but this may very well be my slow connection at work. 

> -rw-r--r--@ 1 colterwehmeier  staff   102M Dec  3 16:38 AB_.mp4
> -rw-r--r--@ 1 colterwehmeier  staff   761M Dec  3 16:42 CSC_.mp4
> -rw-r--r--@ 1 colterwehmeier  staff    78M Aug 28 06:40 ColterWehmeier-Dariah2021-WorkshopPresentation.mkv
> -rw-r--r--@ 1 colterwehmeier  staff   1.3M Jul 29  2021 DariahAPP_AB.pdf
> -rw-r--r--@ 1 colterwehmeier  staff   884M Dec  3 16:37 GA.mp4
> -rw-r--r--@ 1 colterwehmeier  staff   712M Dec  3 16:47 GR_.mp4
> -rw-r--r--@ 1 colterwehmeier  staff    79M Jul 28  2021 Presentation_GArtopoulos.pdf
> -rw-r--r--@ 1 colterwehmeier  staff    14M Jul 27  2021 Presentation_GRedaelli.pdf
> -rw-r--r--@ 1 colterwehmeier  staff   5.7M Jul 27  2021 Presentation_Smaniotto.pdf
> -rw-r--r--@ 1 colterwehmeier  staff   119M Jul 28  2021 Workshop END.pdf
> -rw-r--r--@ 1 colterwehmeier  staff   1.8M Jul 28  2021 Workshop Introduction_GArtopoulos.pdf


Thanks,
Colter

**Comment by VickyGarnett** [comment]
Hi Colter,

We don't really have a way of hosting large media files, just images.  Instead, we recommend that videos are uploaded to YouTube, Vimeo or Nakala, and the video ID is then added using the VideoCard option in the CMS.  

For PDFs, we recommend using HAL or Zenodo and adding the link from there, or alternatively if you have a local institutional repository that is guaranteed to be open and sustainable, you could link to it from there.

I hope that helps.  If you're still having problems, let me know!

Vicky

**Comment by Chopium** [comment]
Wonderful! I swapped over to those hosting services for simplicity and submitted the resource. Did you all have a chance to review? We are publishing a journal soon and would love to cite the resource along with the workshop proceedings.

**Comment by VickyGarnett** [comment]
I haven't had a chance yet, but I see it in the list.  I'll try to get to it by the end of the week.  Thanks!  V
