### ISSUE TITLE
TOC is no longer on the side in Firefox and Chrome

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#25]
Hm.. I just discovered that Firefox and Chrome display our TOC differently than Safari. Something's not right with when the stacking happens...

In Safari, on my laptop, at full screen:

<img width="1440" alt="Снимок экрана 2019-12-10 в 07 36 40" src="https://user-images.githubusercontent.com/5304839/70502018-ee0d3300-1b1f-11ea-85b9-c15eb529c858.png">

In Firefox, on my laptop, at full screen:

![Снимок экрана 2019-12-10 в 07 36 13](https://user-images.githubusercontent.com/5304839/70502033-f9605e80-1b1f-11ea-8b11-ad98fd32bcba.png)

Chrome does the same thing as Firefox. 

This doesn't make sense. @stefanprobst could you please take a look into this?

**Comment by stefanprobst** [comment]
i can't test on Safari, but Firefox and Chrome work correctly for me and break the toc to the side on viewports wider than 1600px.

**Comment by ttasovac** [comment]
But this doesn't happen on Safari. As you can see in the attached screenshot, the viewport is 1440px but TOC is still to the right of the main content.

<img width="1552" alt="Снимок экрана 2020-03-08 в 14 59 49" src="https://user-images.githubusercontent.com/5304839/76164263-c42ed100-614d-11ea-9078-57df8fcadac9.png">

Is there any way for you to check what's going on there without using Safari yourself?

**Comment by stefanprobst** [comment]
I'll take a look this week. my guess is some webkit weirdness with rel. units in mediaqueries

**Comment by stefanprobst** [comment]
can you check #47 preview pls?

**Comment by stefanprobst** [comment]
@ttasovac since you merged #47, is this now fixed?
