### ISSUE TITLE
[new resource]: 

### ISSUE THREAD

**Issue by cinkova** [DARIAH-ERIC/dariah-campus#255]
### Title of the resource

Corpus Design, Search, and Annotation for Beginners

### Authors, editors and contributors

Silvie Cinková, Václav Cvrček, Maarten Janssen, Michal Křen

### Topics (keywords)

XML, TEI, TEITOK, Digital Archives, Editing tools, Repositories & collections, Scholarly editions, Scholarly practice, Training and education,corpus, CQL, Big data, Data modeling, Universal Dependencies,  NLP, Text mining

### Learning outcomes

You will learn:

-  the basics of the [XML-TEI](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/index.html) format, the lingua franca of digital literary scholars and corpus designers; 
- to enrich your texts with linguistic annotation (mainly lemmatization and morphological as well as syntactic markup), using the well-established multilingual tagset of [Universal Dependencies](universaldependencies.org);
- to understand the Universal Dependencies notation; 
- to extract information from your corpus, using the [Corpus Query Language](https://cwb.sourceforge.io/files/CQP_Manual/), also a standard in corpus linguistics, and [PMLTQ](https://lindat.mff.cuni.cz/services/pmltq/#!/home), a user-friendly language for querying syntactic dependency trees;
- to evaluate the statistical significance of your observations.

All these skills will help you mine information from texts. 

No programming is included. You are going to run all the tools in [TEITOK](http://www.teitok.org/), a corpus editor specifically developed for XML-TEI texts. It will take care of your XML-TEI markup while adding the linguistic annotation.   
 

### Abstract

This is the content of the Prague Beginner Training School of Corpus Design, Search, and Annotation. The students are guided through worked examples and a number of exercises to be able to build, search, edit and annotate their own text collections, using state-of-the-art NLP tools and cross-linguistically universal linguistic notation.

**Comment by cinkova** [comment]
Maarten Janssen: https://github.com/maartenpt
vaclav.cvrcek@ff.cuni.cz
Michal Křen https://github.com/michkren

**Comment by VickyGarnett** [comment]
Hi Silvie,

Thanks for sending this through!  I've entered all the authors into the system now, so we're ready to move on to producing the materials now.  I think it would be useful for us to have a meeting to for a plan of how to do this, and to make sure there is all the required information there.

Another note - please make sure you have images of all the authors - ideally in square format - that we can add to this resource before it's published.

Thanks :)

V
