### ISSUE TITLE
[new resource]: 

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#258]
### Title of the resource

Visual Data Discovery for the SSH Context

### Resource type

External Resource

### Authors, editors and contributors

Michela Vignoli, Lottie Provost

### Topics (keywords)

Data Visualisation, DH, Open Access, Open Science, Scholarly Practice, Training and Education

### Abstract

The training session is dedicated to Visual Data Discovery in the Social Sciences and Humanities and shows how the GoTriple platform will support exploring research topics with visual search. The added value of knowledge maps and streamgraphs for research discovery are also examined.

**Comment by VickyGarnett** [comment]
Hi Lottie - thank for this.  I've just entered Michela into the system.  It'll take a few mins to update, but by this afternoon you should be fine to proceed with creating that resource.  Thanks - V :)

**Comment by LottieProvost** [comment]
Hi Vicky,

that's great news thank you.

I wish you a lovely holiday !

Lottie

Le lun. 20 déc. 2021 à 13:32, VickyGarnett ***@***.***> a
écrit :
