### ISSUE TITLE
[new resource]: GeoHumanities Learning Materials

### ISSUE THREAD

**Issue by RebeccaKahn** [DARIAH-ERIC/dariah-campus#260]
### Title of the resource

Geographical Text Analysis (GTA) Tutorial

### Authors, editors and contributors

Katherine Bellamy, Piraye Hacıgüzeller, Rebecca Kahn, Patricia Murrieta-Flores

### Topics (keywords)

Spatial Humanities, Geographical Text Analysis, Data Visualisation

### Learning outcomes

By the end of this tutorial, participants will be familiar with the tools and workflow for analysing the place names (toponyms) in a textaul source, be able to add accurate georeferences to these toponyms, and visualise them using maps. 

### Abstract

Geographical Text Analysis (GTA) is a relatively recent development in the approach to studying, analysing, and extracting the content of textual sources. Combining techniques from Natural Language Processing (NLP), Corpus Linguistics, and Geographic Information Systems (GIS), GTA offers a new methodology for employing these computational tools in Humanities research. The development of this methodology by researchers at Lancaster University builds upon the ‘distant reading’ approach coined by Franco Moretti in the field of Literature.  With a focused interest in querying the geographic nature of textual sources, GTA focuses on the identification, manipulation, and analysis of spatial information on a large scale. 
The following points briefly summarise how this process works, and what the tutorial will teach:
1)	Use of NLP techniques to automatically identify proper nouns (this may be augmented/refined through the use of ontologies designed specifically for a certain corpus/subject interest).
2)	Assigning coordinates automatically to place-names in the corpus by matching these to place-names in a geographical dictionary or gazetteer, a technique called geoparsing.
3)	Implementation of Corpus Linguistics techniques to reveal significant linguistic regularities or patterns. This is particularly important for verifying key concepts as they relate to individual places.
4)	The mapping of identified data and, subsequently, the spatial analysis of this data using GIS software.

**Comment by VickyGarnett** [comment]
Hi Rebecca - thanks for sending this in.  Could you let us know what kind of resource this is going to be, e.g. Hosted Resource, External Resource?  If you're not sure which is which, you can check here: https://campus.dariah.eu/docs/types-of-resources

Thanks :) - V

**Comment by RebeccaKahn** [comment]
Hello Vicky - apologies, I forgot to mark that. I think it makes the most sense as a Hosted Resource, if that works for you folks. Thanks so much!

R

**Comment by VickyGarnett** [comment]
That's great, thanks for getting back to me so quickly.  The names are all in the system now, so you can go ahead and make a start using the CMS:  https://campus.dariah.eu/admin

We have a step-by-step guide to the CMS that you can refer to here: https://campus.dariah.eu/docs/using-the-content-management-system

If you have any questions, do give me a shout :) Thanks - V

**Comment by RebeccaKahn** [comment]
Thanks, I will definitely shout if I need anything, although the guide is great!
best
R

**Comment by VickyGarnett** [comment]
Published, so closing proposal :)
