### ISSUE TITLE
set the min-height of the course registry iFrame

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#27]
I changed the iFrame link to the Course Registry when they switched to the new design and that's fine. The problem is that the iFrame now doesn't show enough content. For instance:

<img width="1322" alt="Снимок экрана 2019-12-10 в 16 32 24" src="https://user-images.githubusercontent.com/5304839/70544049-b926cd80-1b6b-11ea-93e6-4f415b8859dd.png">

This is on my laptop, after clicking on the "Filter" button. We don't see all the filters.

I tried the obvious —  setting min-height on iFrame etc., but that's not enough, I assume, because of the flex layout or something like that.

We need to make this iFrame by default bigger, i.e. taller, so that it pushes the footer beyond the viewport in order to allow for more of its content to be shown...

**Comment by ttasovac** [comment]
Hi @stefanprobst 

thanks a lot for https://github.com/DARIAH-ERIC/dariah-campus/commit/f3eba3e2253ad5cee6e2f31ec2472a5fc8a1df52! 

One additional question —  do you know why the map is no longer loading? I'm getting a bunch of 403's. I assume this is not on our side. Should I take this up with the Course Registry people?

**Comment by ttasovac** [comment]
<img width="1388" alt="Скриншот 2019-12-11 12 08 17" src="https://user-images.githubusercontent.com/5304839/70616582-14f66280-1c0f-11ea-932a-2aadf305a7a4.png">

**Comment by stefanprobst** [comment]
hmm, i just tried and it did load for me. 403 looks like this was a permissions error on their side, yes

**Comment by ttasovac** [comment]
for me it only works locally, but not on netlify's servers. i will check out the DHCR people...
