### ISSUE TITLE
security alert for some dependencies

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#278]
### Bug report

Stefan, I made you admin of this repo so that you can see https://github.com/DARIAH-ERIC/dariah-campus/security/dependabot (otherwise, I don't think you get these alerts)

Could you, when you have a moment, try to upgrade the packages that can be upgraded... 

Many thanks in advance.

All best,
Toma

**Comment by stefanprobst** [comment]
these alerts are all about dependencies which are used by packages we use in *development*, so these don't actually get deployed. this is a known issue with dependabot alerts, and i'd actually recommend turning them off since they mostly only create noise.

**Comment by ttasovac** [comment]
done!
