### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#31]
- we need to install a Google Anayltics plugin for Gatsby
- i'll get the credentials

**Comment by elizapapaki** [comment]
- I created a new property for DARIAH-Campus on Google Analytics (site tag emailed), let me know if it works

**Comment by stefanprobst** [comment]
somebody needs to send me the tracking id, so i can add the analytics plugin

**Comment by ttasovac** [comment]
Added in #46
