### ISSUE TITLE
Turborepo?

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#325]
### Bug report

Dear Stefan,

I am just parking this here so that I don't forget. No need to respond until you have more time.

I'm wondering whether it would make sense to start using [Turborepo](https://turborepo.org/docs/getting-started) to build D-C. It's now part of Vercel and it comes with remote caching. 

I have 0 experience with this, but would love to hear from you whether you think we could/should experiment with this...

All best,
Toma

**Comment by stefanprobst** [comment]
i have no experience with it - but isn't it a monorepo tool?

**Comment by ttasovac** [comment]
yes, but i thought that perhaps it would also be useful for us. that's why i wanted to check with you. but it's no big deal. if you don't see any use in it, i'll forget about it.
