### ISSUE TITLE
[new resource]: The Importance of User-Centred Design for Open Science

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#378]
### Title of the resource

The Importance of User-Centred Design for Open Science

### Authors, editors and contributors

Paula Forbes, Francesca Di Donato, Lottie Provost

### Topics (keywords)

Training and Education, Open science, DH, Project management

### Abstract

This training event is devoted specifically to giving an understanding of the importance of the co-design process and the impact it has on the development of digital tools such as the GoTriple Discovery platform. It provides insight on the importance of end-user needs in the design of a discovery platform, the methods used in the TRIPLE Project to consider user-needs and showcases the next steps for the GoTriple platform now that the Beta version is released.

**Comment by VickyGarnett** [comment]
Hi Lottie - I've added Paula to the list of authors, so that's now ready to progress to creating the full resource.

Thanks - V :)
