### ISSUE TITLE
[new resource]: 

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#409]
### Title of the resource

The Importance of User Centred Design for Open Science

### Resource type

_External Resource_

### Authors, editors and contributors

Paula Forbes, Francesca Di Donato, Lottie Provost

### Topics (keywords)

DH, Open Access, Open Science, Open Education, Project Management, Training and Education, Scholarly Practice

### Abstract

This training event is be devoted specifically to giving an understanding of the importance of the co-design process and the impact it has on the development of digital tools such as the GoTriple discovery platform. It will provide answers to the following questions, among others:
Why is it important to consider end-user needs when designing a discovery platform?
Which methods did the TRIPLE project use to do this and what kind of insights has it given?
Why is having SSH researchers on-board with the design process so important?

**Comment by VickyGarnett** [comment]
Hi Lottie - this all looks grand, and those authors are already in the system, so please go ahead with creating the resource!  Thanks - V :)

**Comment by LottieProvost** [comment]
Thanks Vicky !

All the best,

L

Le mar. 1 mars 2022 à 10:50, VickyGarnett ***@***.***> a
écrit :

**Comment by VickyGarnett** [comment]
How are you getting on with this resource, Lottie?  Have I missed something I was supposed to do?  Cheers - V :)

**Comment by LottieProvost** [comment]
Hi Vicky,

thanks for you email.  I actually still have to finish writing so don't
worry there is nothing for you to do for the moment.  Thanks :-)

Best,

Lottie

Le mar. 29 mars 2022 à 15:23, VickyGarnett ***@***.***> a
écrit :
