### ISSUE TITLE
[new resource]: The GoTriple Trust Building System Training

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#430]
### Title of the resource

The GoTriple Trust Building System 

### Authors, editors and contributors

Maxime Bouillard, Gaël van Weyenberg, Lottie Provost,  Erzsébet Tóth-Czifra Toth Czifra

### Topics (keywords)

Citizen science, DH, Open Science, Training and Education 

### Learning outcomes

After watching this session you should be able to: 
- Create a profile
- Post a request
- Interact with peers (invitations, introductions, group creation)

### Abstract

This training event is devoted specifically to getting acquainted with the GoTriple Trust Building System (TBS), a tool that enables SSH researchers to find reliable partners and connect with them through their network.

**Comment by LottieProvost** [comment]
@VickyGarnett Hi Vicky, I just realised that I didn't fill in the 'Resource type' field (I usually put 'External resource').. I hope it's not a problem. 
Thanks, Lottie-

**Comment by VickyGarnett** [comment]
Hi Lottie,  that's no problem :)  I've added those extra authors now.  As before, if you can include square format images for those authors when you're creating the resource, that would be super!  Thanks - V :)

**Comment by LottieProvost** [comment]
Will do for the photos !

Thanks a lot Vicky,

Lottie

Le jeu. 7 avr. 2022 à 10:10, VickyGarnett ***@***.***> a
écrit :

**Comment by VickyGarnett** [comment]
Hi Lottie - for some reason we seem to be missing the image for this resource, and it's preventing us from publishing.  Could you email me the image for the video for this resource asap, please?  We'll add it manually from our side.  Sorry about this, I'm not sure what has happened here.

Thanks

Vicky
