### ISSUE TITLE
[new resource]: Multilingual Vocabularies for the Social sciences and Humanities Training

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#435]
### Title of the resource

Multilingual Vocabularies for the Social sciences and Humanities

### Resource type

External Resource

### Authors, editors and contributors

Daan Broeder, Haris Georgiadis, Nikos Vasilogamvrakis, Iraklis Katsaloulis, Lottie Provost, Francesca Di Donato

### Topics (keywords)

Open Science, Controlled Vocabularies, DH, Training and Education

### Learning outcomes

After watching this video you should be able to: 
- Explain what SSH vocabularies are and why they are so important. 
- Understand the steps to create a multilingual SSH vocabulary.
- Identify management needs related to the large variety of vocabularies in the SSH.
- Summarise how to build an interoperable infrastructure for vocabularies. 

### Abstract

This training event from the TRIPLE Project is jointly organised with the SSHOC Project and is dedicated to the creation, use and management of controlled vocabularies in the SSH.

**Comment by VickyGarnett** [comment]
HI Lottie,

Apologies, I thought I'd done this one.  The new people have been added to the system, so you can proceed with this resource.  Thanks V - :)
