### ISSUE TITLE
RSETraining2019: Problems with preview and pull requests

### ISSUE THREAD

**Issue by n-romanova** [DARIAH-ERIC/dariah-campus#44]
1)
The new version of the Events template does not require closing </Speaker></Speakers> tags at the end of the list of speakers in Sessions, and, indeed, I cannot commit to master (my own branch) if I have those. So I deleted all the closing tags and managed to push origin (please see https://github.com/n-romanova/dariah-campus/tree/master/contents/events/RSETraining2019).

At the same time, I see that the other two events currently on GitHub (the sample one and the winter school 2019) do have those closing tags.

Now, hen I try to create a pull request to merge with the main branch, I get failure to deploy messages that I cannot decode (e.g. error "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle).

I have been playing with pulling requests to try to understand what I may have done wrong with the encoding but unfortunately got nowhere so far.

2)
When, on the other hand, I am trying to preview the site locally, the compiler requires me to have those closing </Speaker></Speakers> tags, which I dutifully put back in, after which it reports that the site has been compiled successfully - but, unfortunately, it is not rendered in the browser. The same thing happened when I was using npm as per old instructions (for preview on Windows) and is happening now that I am using yarn (as per new instructions on Campus).

If you have any ideas as to what I may be doing wrong, I'd be most grateful!
You can see the files that I added onto my branch at https://github.com/n-romanova/dariah-campus/tree/master/contents/events/RSETraining2019

![image](https://user-images.githubusercontent.com/53479279/76070057-d7923e80-5f8b-11ea-8067-a95b48e55f74.png)

**Comment by ttasovac** [comment]
You definitely want to close those.

Also, you don't seem to be pointing to the people.yaml file at all, which is where you would find the image for each speaker etc. 

Check out the speakers in desir_winterschool2019. You will see something like this:

```html
<Speakers>
<Speaker speaker="mariafernanda-rollo">

Fernanda has a PhD in Contemporary History from the Faculdade de Ciências
Sociais e Humanidades, Universidade Nova de Lisboa and is Associate Professor in
the same faculty. Researcher and former President of the Institute for
Contemporary History, Prof. Fernanda Rollo has coordinated research projects and
has several texts published in the areas of Economic and Social History, history
of Portugal, and the history of innovation and organization of science. She is a
former Secretary of State for Science, Technology and Higher Education.

</Speaker>
</Speakers>
```

The important bit is the attribute `speaker="mariafernanda-rollo"`, this is set up to point to /contents/data/person.yaml file and inside it to the speaker whose slug is "mariafernanda-rollo".

```yaml
- name: Maria Fernanda Rollo
  slug: mariafernanda-rollo
  avatar: ../images/authors/mariafernanda-rollo.jpg
  orcid: 0000-0002-2249-7279
```

It's in the yaml file that you set the avatar image, orcid id, twitter, website, email, linkedIn etc. for each individual speaker. You can also write their whole biography in the yaml file, or you can write it in session.mdx file...

So, please try the following:

- close all `</Speaker>` and `</Speaker>` tags
- make sure that each `<Speaker>` has a speaker attribute pointing to a record in the person.yaml file
- make sure that each record in the yaml file has the avatar and at least one other id (website, email and/or orcid)

commit and push again ... your changes will be added to this pull request... and then we'll take another look.

All best,
Toma

**Comment by n-romanova** [comment]
Thanks Toma! Deleting closing tags was the only way I could get my files to commit (removing references to people.yaml was another misguided attempt to get things to work).

I have now put all the tags back and made sure that all the slugs are in place in the open <Speaker> tags but I cannot commit any more. Below is the message I am getting.
Hope this makes sense.

![image](https://user-images.githubusercontent.com/53479279/76100030-ebf22d80-5fc3-11ea-8f45-ad240f5f79b9.png)
![image](https://user-images.githubusercontent.com/53479279/76100065-f7455900-5fc3-11ea-9619-d1bc20606bc6.png)
