### ISSUE TITLE
Netlify checks ok, but the preview link still doesn't work properly

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#45]
Dear Stefan,

as you can see in #43, I closed the missing tags, previewed the site locally and pushed the changes to Natasha's pull request. We passed all the checks and Netlify generated a preview link:
https://deploy-preview-43--d-c.netlify.com but when you click on the link the site flashes for a second and is then replaced by a blank page.

I haven't had this problem before and I really don't know what to do about it. We're not ready yet to merge this into the master, but when we do, we have to make sure that it will work.

Could you please look into this?

All best,
Toma

**Comment by stefanprobst** [comment]
I can take a look this week, yes

**Comment by stefanprobst** [comment]
pushed the lock file from master - seems to work ok - people need to (i) use yarn not npm and (ii) not change deps/push a modified yarn.lock

**Comment by ttasovac** [comment]
ok, just to clarify this. we changed the instructions to use only yarn, that's clear. but: 

- we currently haver `package.json` and `package-lock.json` in the master branch. should i remove `package-lock.json` ? if i understand things correctly, we don't need it if we're sticking with `yarn`. 

- `yarn.lock` should be committed to git, but we, on the editorial side, should make sure that we don't accept any changes to `yarn.lock`.  when new contributors do yarn install, that will basically install all the dependencies etc. which are in yarn.lock. is this correct?

- if the above is correct, when do we (on the editorial side of D-C), if ever, need to do `yarn upgrade`?

I haven't merged the pull request yet, but the netlify link looks good now.

**Comment by stefanprobst** [comment]
* i have removed `package-lock.json` in my commit to #43, see https://github.com/DARIAH-ERIC/dariah-campus/pull/43/commits/9c601ad59b50d91b3a0f5e8dc8460a3c99202efb
this is the lock file created by npm (similar to yarn.lock)
* we definitely want to keep `package.json`
* yes `yarn.lock` should be commited to git, and yes it defines what people will get with `yarn install`. it gives us at least a little bit control over people's build environment
* except for security fixes for *specific* packages, we do *not* want to `yarn upgrade`

* that said, if we find the time it would still make sense to figure out what exactly broke with the changed deps in #43
