### ISSUE TITLE
[new resource]: The GoTriple Pundit Annotation Tool training

### ISSUE THREAD

**Issue by LottieProvost** [DARIAH-ERIC/dariah-campus#451]
### Title of the resource

The GoTriple Pundit Annotation Tool

### Resource type

External Resource

### Authors, editors and contributors

Tiziana Lombardo, Sona Arasteh, Giulio Andreini, Francesca Di Donato, Lottie Provost

### Topics (keywords)

Open Science, Editing Tools, EOSC, DH, Scholarly Practice, Training and Education

### Learning outcomes

After watching this video you should ...  
- Know the purposes and functionalities of the Pundit Annotation Tool 
- Understand how Pundit can be used in the SSH research context

### Abstract

This training webinar will be dedicated to the GoTriple Pundit Annotation Tool and will present the purpose, functionalities, perspectives and a roadmap of Pundit, including the plan to enlist it as a EOSC service. A researcher will demonstrate how Pundit can be used in the SSH research context and a step-by-step guide will showcase how to use Pundit from GoTriple and elsewhere, from registering to annotating web documents.

**Comment by VickyGarnett** [comment]
Hi Lottie - the new authors on this resource have been added to the system.  Thanks - Vicky
