### ISSUE TITLE
[new resource]: What can I do with this messy spreadsheet? Converting from Excel sheets to fully compliant EAD-XML files

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#539]
### Title of the resource

What can I do with this messy spreadsheet? Converting from Excel sheets to fully compliant EAD-XML files

### Resource type

External Resource

### Authors, editors and contributors

Herminio Garcia González

### Topics (keywords)

Big data, Data management, eHeritage, Metadata, Repositories & Collections, XML

### Learning outcomes

- Understand the procedure for producing EAD files from an Excel spreadsheet using OpenRefine

### Abstract

Many Galleries, Libraries, Archives, and Museums (GLAM) face difficulties sharing their collections meta-data in standardised and sustainable ways due to the absence of in-house Information Technology (IT) support or capabilities. This situation means that staff rely on more familiar general purpose office programs like text processors, spreadsheets, or low-code databases. However, while these tools offer an easy approach for data registration and digitisation they don’t allow for more advanced uses. This blog explains a procedure for producing EAD files from an Excel spreadsheet using OpenRefine.

**Comment by VickyGarnett** [comment]
Hi Claire - I have added Herminio to the 'Authors' list, so you can proceed to drafting up this resource.  At your earliest convenience, please could you include a square photo of Herminio to his profile in the 'People' tab.  Thanks :) - Vicky

**Comment by VickyGarnett** [comment]
Resource published, closing issue
