### ISSUE TITLE
[new resource]: Spatial Queries and the First Deportations from Slovakia

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#540]
### Title of the resource

Spatial Queries and the First Deportations from Slovakia

### Resource type

External Resource

### Authors, editors and contributors

Michal Frankl

### Topics (keywords)

Big data, Computational imaging, Data visualisation, eHeritage, Geotagging, Metadata, Repositories & Collections

### Learning outcomes

- Recognise the benefit of using Geonames (or any similar resource) and spatial queries - with place coordinates, historical borders and spatial queries - to ask any new research questions or rephrase existing ones throughout the research process
- Learn how these standardisation can also make the building of visualisations (e.g. in the form of maps) much smoother
- Understand how visualisations can reveal connections and patterns that otherwise would remain invisible and hence feed back into the research process

### Abstract

This practically oriented blog describes the process of analysis and the approaches as well as tools used and shows how a spatially enabled database can be made useful in the research process in the humanities. While none of the steps described is path-breaking from the technological point of view, the described workflow seems to be rarely, if at all, used by Holocaust historians.

**Comment by VickyGarnett** [comment]
Hi Claire, Michal is now in the system, so you can proceed to draft this resource.  Please add a square photo to his profile at your earliest convenience.  Thanks :) - Vicky

**Comment by VickyGarnett** [comment]
Resource published, closing proposal
