### ISSUE TITLE
[new resource]: Using Named Entity Recognition to Enhance Access to a Museum Catalog

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#543]
### Title of the resource

Using Named Entity Recognition to Enhance Access to a Museum Catalog

### Resource type

External Resource

### Authors, editors and contributors

Ivelina Nikolova & Michael Levy

### Topics (keywords)

Big data, Data visualisation, Digital archives, eHeritage, Geotagging, Metadata, Repositories & Collections

### Learning outcomes

- Understand the use of automatic extraction of person names 
- Learn about the location extraction from text

### Abstract

Digital technologies are successfully applied in cultural heritage projects supporting digitisation of cultural objects, metadata creation, metadata maintenance, creation of digital infrastructure for cultural heritage research and many others. When we discuss archival digital textual content, some of the most imminent tasks are related to automatic metadata generation, searchability and preservation, and these can be helped by services for automatic semantic annotation. In this blog we discuss the applicability of such services for automatic extraction of person names and locations from Oral History Transcripts provided by the United States Holocaust Memorial Museum (USHMM). The algorithms for automatic information extraction can work with comparatively high accuracy when applied in a close domain, they are especially helpful and could greatly speed up the human work when large volumes of data are to be processed.

**Comment by VickyGarnett** [comment]
Hi Claire, these authors are in the system and you can continue with drafting the resources.  As ever please add photos.  Thanks :) - Vicky

**Comment by VickyGarnett** [comment]
resource published, closing issue
