### ISSUE TITLE
[new resource]: quod: A Tool for Querying and Organising Digitised Historical Documents

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#544]
### Title of the resource

quod: A Tool for Querying and Organising Digitised Historical Documents

### Authors, editors and contributors

Reinier De Valk

### Topics (keywords)

Big data, Digital archives, eHeritage, Information Architecture, Metadata, Repositories & Collections

### Learning outcomes

- Understand the prototype tool for OCRing and querying digitised historical documents, "quod", which can be used for organising large collections of such documents

### Abstract

The archives of the International Tracing Service (ITS) in Bad Arolsen, Germany, which focus on the topics of wartime incarceration, forced labour, and liberated survivors, have among their holdings a collection of approximately 4.2 million images (photographs) of documents that have been rearranged without taking into account their provenance. This makes it difficult — or at least highly laborious — to determine, for example, to which subcollection an image originally belongs, or, conversely, to find documents from certain subcollections; or to organise the collections in certain ways. The usability of this collection can be improved significantly (i) by unlocking it, i.e., by making it machine-readable and thereby open to querying, and (ii) by organising it automatically. This blog post demonstrates how the former can be seen as a prerequisite for the latter, which is the harder task.

**Comment by VickyGarnett** [comment]
Resource published - closing issue
