### ISSUE TITLE
[new resource]: The Learning Curve in Sharing Data with the EHRI Project: The Example of a Memorial Site, Kazerne Dossin, Mechelen

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#545]
### Title of the resource

The Learning Curve in Sharing Data with the EHRI Project: The Example of a Memorial Site, Kazerne Dossin, Mechelen

### Resource type

External Resource

### Authors, editors and contributors

Dorien Styven, Marius Caragea & Veerle Vanden Daelen

### Topics (keywords)

Big data, Digital archives, eHeritage, Information Architecture, Metadata, Repositories & Collections, XML

### Learning outcomes

- Understand how archives and memorial sites like Kazerne Dossin can share their data and what  evolution they went through while standardising descriptions 
- Learn about the tools that EHRI provided to optimise the workflow for collection holding institutes

### Abstract

Kazerne Dossin – Memorial, Museum and Documentation Centre on Holocaust and Human Rights opened its doors on 1st December 2012. The institute inherited its archival collections from its predecessor, the Jewish Museum of Deportation and Resistance (JMDR). The JMDR had been inaugurated in 1995 at the former SS-Sammellager Mecheln, better known as the Dossin barracks, in Belgium. Between the summer of 1942 and 1944 over 25,500 Jews, Roma and Sinti were deported from here to concentration camps the East, mostly to Auschwitz-Birkenau. From the mid-1990s onwards the JMDR collected archival materials on the Holocaust in Belgium. The way in which these were catalogued and made available to the public changed dramatically over the past few years as Kazerne Dossin and EHRI became partners in sharing (meta)data with a broader audience. Using the example of the Lewkowicz family collection (unique, persistent identifier KD_00404) this article focuses on the evolution Kazerne Dossin went through while standardizing descriptions, and on the tools EHRI provided to optimize the workflow for collection holding institutes, a process from which Kazerne Dossin benefited as a test case.

**Comment by VickyGarnett** [comment]
HI Claire, all good to proceed, thanks :) V

**Comment by VickyGarnett** [comment]
resource published, closing issue
