### ISSUE TITLE
[new resource]: Georeferencing Service for Archives

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#546]
### Title of the resource

Georeferencing Service for Archives

### Resource type

External Resource

### Authors, editors and contributors

Annelies van Nispen

### Topics (keywords)

Big data, Data visualisation, Digital archives, eHeritage, Geotagging, Metadata, Ontologies, Repositories & Collections

### Learning outcomes

- Understand how different pieces of information can be identified in archival descriptions and be used to enrich the metadata and the EHRI vocabularies

### Abstract

Archives often have the wish to make their collections searchable and findable on a map like Google Maps or Open Street Map. This is a nice interface for users on which they can zoom in on a specific geographic location and see what collections are linked to it. This promise of a user friendly geographic search interface is appealing. But for most archives identifying geographical information in their collections and develop services for their users is still often in an experimental or first phase. 

In EHRI knowledge about Named Entity Recognition (NER) is available, as is in many larger European projects or research infrastructures. This technique is used to scan the metadata (or OCR’d archival material) and identify geographic information, but it is also possible to identify persons, organisations, keywords or other specific information units.

**Comment by VickyGarnett** [comment]
HI Claire, all good to proceed, thanks :) - V

**Comment by VickyGarnett** [comment]
resource published, closing issue
