### ISSUE TITLE
[new resource]: More Watching, Less Searching: Repurposing Fortunoff Archive Metadata for Visual Searching

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#547]
### Title of the resource

More Watching, Less Searching: Repurposing Fortunoff Archive Metadata for Visual Searching

### Resource type

External Resource

### Authors, editors and contributors

Stephen Naron & Jake Kara

### Topics (keywords)

Big data, Data visualisation, Digital archives, eHeritage, Metadata, Repositories & Collections

### Learning outcomes

- Learn about Visual Search, which is a tool for both data visualisation and collection discovery

### Abstract

The Fortunoff Video Archive For Holocaust Testimonies and the Yale Digital Humanities Lab (DHLab) began building a Visual Search tool in 2019 in order to provide a simple overview of the Fortunoff Archive’s collection and enable quick filtering and discovery of relevant testimonies. The Visual Search is a tool for both data visualisation and collection discovery. The default state of the tool displays the entire collection. As the user interactively applies filters the interface is updated to reflect only the resulting subset of the collection. The user interface is composed of the following sections, arranged in a single column layout: a prose summary, a visualization cluster, a subject heading pool, and a result list.

**Comment by VickyGarnett** [comment]
Hi Claire, all good to proceed, thanks :) - V

**Comment by VickyGarnett** [comment]
Resource published, closing proposal
