### ISSUE TITLE
[new resource]: Extracting CSV data from the EHRI Search API

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#548]
### Title of the resource

Extracting CSV data from the EHRI Search API

### Resource type

External Resource

### Authors, editors and contributors

Mike Bryant

### Topics (keywords)

Training & Education, Data management

### Learning outcomes

- Understand how to use popular command-line tools (available on MacOS, Linux, and Windows) extract data from the EHRI Search API
- Understand how to convert the extracted data to CSV, where it can be imported into Excel or a relational database

### Abstract

The EHRI (European Holocaust Research Infrastructure) Search API provides a way of retrieving information about items in the EHRI portal in JSON (JavaScript Object Notation) format by making HTTP requests to particular URLs. Instead of using a web browser to make web requests which return HTML pages, we use a command line tool (CuRL) that fetches structured data we can then transform into CSV (comma separated values), a format we can then import into a spreadsheet like Excel or Google Docs.

**Comment by VickyGarnett** [comment]
Hi Claire, all good to proceed, although unless this resource contains critique and discussion of pedagogical theory, I would remove the keyword 'Training and Education', thanks :) - V

**Comment by VickyGarnett** [comment]
Resource published
