### ISSUE TITLE
[new resource]: Entity Matching

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#549]
### Title of the resource

Entity Matching

### Resource type

External Resource

### Authors, editors and contributors

Rachel Pistol

### Topics (keywords)

Training & Education, Data visualisation, Data management, eHeritage

### Learning outcomes

- Understand how the EHRI (European Holocaust Research Infrastructure) Entity Matching tool can be used to create data visualisations using mapping tools such as Google Maps.

### Abstract

At EHRI (European Holocaust Research Infrastructure), we are constantly looking at Digital Tools that can assist in the research of Holocaust and refugee related topics. We hope to make these tools as accessible as possible so that researchers who have no experience with digital tools will consider trying new ways of using their data. A number of datasets presented at EHRI related events contain place names that researchers wish to present on maps. In order to accurately display locations, latitude and longitude coordinates are essential. EHRI has created an entity matching tool to help researchers find coordinates for present day locations.

**Comment by VickyGarnett** [comment]
Hi Claire, that author is in the system.  If you can remove 'Training and Education' as a keyword, this is good to go.  Thanks :) - V

**Comment by VickyGarnett** [comment]
Resource published, closing issue
