### ISSUE TITLE
[new resource]: Using OpenCV for Face Detection

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#550]
### Title of the resource

Using OpenCV for Face Detection

### Resource type

External Resource

### Authors, editors and contributors

Mike Bryant

### Topics (keywords)

eHeritage, Training & Education, Data management, Data visualisation

### Learning outcomes

- Understand how to get started in experimenting with OpenCV.

### Abstract

OpenCV is a very popular, free and open source software system used for a large variety of computer vision applications. This article is intended to help you get started in experimenting with OpenCV and as an interesting example the article discusses how to detect faces in images.

**Comment by VickyGarnett** [comment]
Hi Claire, Mike's already in the system.  Again, if you can remove 'Training and Education' as a keyword, unless this resource discusses pedagogical practice, that would be great.  Thanks :) - V

**Comment by VickyGarnett** [comment]
Resource published - closing issue
