### ISSUE TITLE
[new resource]: Importing tables from websites into spreadsheets

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#551]
### Title of the resource

Importing tables from websites into spreadsheets

### Resource type

External Resource

### Authors, editors and contributors

Rachel Pistol

### Topics (keywords)

Training & Education, Data management

### Learning outcomes

- Learn how to quickly create a document list to consult in an archive, or for many other research purposes

### Abstract

Sometimes it can be useful to take information from a website, such as document lists from archives, for future reference. If these items are in a table on a webpage you can download an extension to your browser that will allow you to copy the data from the webpage into a spreadsheet.

**Comment by VickyGarnett** [comment]
Hi Claire - Rachel is already in the system, and again, remove 'Training and Education'.  Otherwise, good to go.  Thanks :) - V

**Comment by VickyGarnett** [comment]
Resource published
