### ISSUE TITLE
[new resource]: Windows Subsystem for Linux (WSL): A convenient way to run Linux tools on a Windows 10 system

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#552]
### Title of the resource

Windows Subsystem for Linux (WSL): A convenient way to run Linux tools on a Windows 10 system

### Resource type

External Resource

### Authors, editors and contributors

Michael Levy & Mike Bryant

### Topics (keywords)

Training & Education, Data management

### Learning outcomes

- Understand how to set-up a working version of this Ubuntu Linux distribution running on your Windows computer (this tutorial is for Windows users)

### Abstract

Linux is a popular operating system and is especially useful for projects involving command-line scripts and programming languages such as Python. Many tools and examples that are of interest to those wishing to explore, experiment,and develop projects for digital humanities or data analysis and other tasks are based on Linux. Mac laptops support Linux fairly easily, and there are many online resources that a Mac user may find helpful. However, until recently, people who have only Windows computers have had a relatively difficult time in accessing programs and techniques that require a Linux operating system. In the recent past, a common way to operate a Linux system on a Windows computer, while continuing to be able to access Windows (i.e., without having to reboot the computer into a Linux mode) was through installing VirtualBox, followed by installing a Linux operating system into the VirtualBox environment. At that point, under VirtualBox, it was not always easy or straightforward to configure the Linux system to access network resources that are accessible to the Windows system. For most Windows 10 users, there is now an alternative method of running Linux programs and systems, through Windows Subsystem for Linux (WSL).

**Comment by dirkroorda** [comment]
Is this resource already online somewhere? I would like to point a programmer on a Windows machine to it in order to help in the transition to Linux.

**Comment by ClaireB82** [comment]
Dear Mr Roorda,

The resource isn’t yet on the DARIAH site – that is coming soon!
For now you can find it here: ehri-data-analysis-tools/installing_linux_on_windows at master · EHRI/ehri-data-analysis-tools · GitHub<https://github.com/EHRI/ehri-data-analysis-tools/tree/master/installing_linux_on_windows>

Best wishes,
Claire

**Comment by dirkroorda** [comment]
@ClaireB82 Thanks a lot, very helpful!

**Comment by VickyGarnett** [comment]
HI Claire - Michael and Mike are already in the system, so this can proceed to drafting.  As ever, please take out the T&E tag.  Thanks :)  V

**Comment by VickyGarnett** [comment]
Resource published
