### ISSUE TITLE
[new resource]: Using spatial data in Tableau

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#553]
### Title of the resource

Using spatial data in Tableau

### Resource type

External Resource

### Authors, editors and contributors

Rachel Pistol

### Topics (keywords)

Training & Education, Data visualisation, Data management, eHeritage

### Learning outcomes

- Examine one aspect of Tableau (data analysis), using mapping that is applied for Holocaust and refugee studies

### Abstract

Tableau is a powerful digital tool for analysing data. In this short guide we will focus on one particular aspect of data analysis using mapping that has particular application for Holocaust and refugee studies. Sometimes just simply mapping your data is not enough, and you want to use other features such as changing the size of a marker above a location in order to demonstrate the number of people from that town or city. Tableau can help with this and can be used for free for 14 days, or is available free of charge to individuals teaching or researching at an academic institution.

**Comment by VickyGarnett** [comment]
Hi Claire - good to go, remove T&E :)  Thanks  V

**Comment by VickyGarnett** [comment]
Resource published, closing issue
