### ISSUE TITLE
[new resource]:  Exploratory Topic Modelling in Python

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#554]
### Title of the resource

 Exploratory Topic Modelling in Python

### Resource type

External Resource

### Authors, editors and contributors

Mike Bryant & Maria Dermentzi

### Topics (keywords)

Training & Education, Data management, Digital Archives, eHeritage

### Learning outcomes

- Understand the process of topic modelling in Python (the tutorial accompanies the article (to be) published in the European Holocaust Research Infrastructure (EHRI) Document Blog entitled "Exploratory Topic Modelling in Python")

### Abstract

Topic modelling is a technique by which documents within a corpus are clustered based on the manner in which certain groups of terms are used together within the text. The commonalities between such term groupings tend to form what we would normally call “topics”, providing a way to automatically categorise documents by their structural content, rather than any a priori knowledge system. Topic modelling is generally most effective when a corpus is large and diverse, so the individual documents within in are not too similar in composition.

**Comment by VickyGarnett** [comment]
Hi Claire, Maria's now in the system,  Remove T&E, all good.  Ta!  V :)

**Comment by VickyGarnett** [comment]
Resource published - closing issue
