### ISSUE TITLE
[new resource]: Topic Modelling Experiments

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#555]
### Title of the resource

Topic Modelling Experiments

### Resource type

External Resource

### Authors, editors and contributors

Maria Dermentzi

### Topics (keywords)

Training & Education, Data management

### Learning outcomes

- Learn about several modelling experiments

### Abstract

This entry provides several modelling experiments using codes that derive from the examples available around the web.

**Comment by VickyGarnett** [comment]
Hi Claire - Maria's in there already.  If you could remove T&E from tags, and expand on the abstract a small bit (not too much, just maybe one or two more sentences) that would be smashing.  E.g. what modelling experiments, and how do they help research?  Thanks :)  V

**Comment by VickyGarnett** [comment]
Resource published, closing issue
