### ISSUE TITLE
[new resource]: How to capture and reference a webpage in your research using Zotero

### ISSUE THREAD

**Issue by ClaireB82** [DARIAH-ERIC/dariah-campus#556]
### Title of the resource

How to capture and reference a webpage in your research using Zotero

### Resource type

External Resource

### Authors, editors and contributors

Rachel Pistol

### Topics (keywords)

Data management

### Learning outcomes

- Understand how to use Zotero to capture webpages that can then be cited in your work

### Abstract

The need to reference webpages in academic work is growing all the time, particularly in the digital humanities. There are many different reference management systems that exist to help researchers sort and find their sources and the most accessible of these is Zotero.

**Comment by VickyGarnett** [comment]
Hi Claire, looks good.  Again, remove T&E unless this directly talks about pedagogical practice.  But you can go on to draft the resource now.  Thanks :)  V

**Comment by ClaireB82** [comment]
Hi Vicky,

Thanks for adding all the authors! I will try to add the content next week – this week won’t be possible – and will address the edits you mention.

Many thanks again!
With best wishes,
Claire
