### ISSUE TITLE
graphQL question: how to get all the speakers in an event

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#56]
The following query gives us titles of "events" on D-C:

```graphql
query myquery {
  allMdx(filter: {frontmatter: {categories: {elemMatch: {slug: {eq: "events"}}}}}) {
    nodes {
      frontmatter {
        title
      }
    }
  }
}
```

How can we query all the speakers in a given event? Speakers are listed in individual sessions, not the index.mdx. 

Many thanks in advance.

**Comment by stefanprobst** [comment]
with our current flat file structure this is not super straightforward unfortunately, but you can e.g. do:

```graphql
{
  speakers: allMdx(filter: {fileInfo: {sourceInstanceName: {eq: "events"}, name: {regex: "/^session/"}}}) {
    group(field: fileInfo___relativeDirectory) {
      fieldValue
      nodes {
        frontmatter {
          speakers {
            name
          }
        }
      }
    }
    distinct(field: frontmatter___speakers___name)
  }
  events: allMdx(filter: {fileInfo: {sourceInstanceName: {eq: "events"}, name: {eq: "index"}}}) {
    group(field: fileInfo___relativeDirectory) {
      fieldValue
      nodes {
        frontmatter {
          title
        }
      }
    }
  }
}
```

we could either hide this in a custom resolver (so you could just query with `query { eventSpeakers(id: "some-event-id") { name }` or adjust our data model to make EventSession a child node of Event (but i'd not want to do this before adding the CMS stuff)

**Comment by ttasovac** [comment]
Thanks a lot! This should do it for now.
