### ISSUE TITLE
Building and Linking Humanities' Digital Spatial Infrastructures for Research

### ISSUE THREAD

**Issue by alexandrapetrulevich** [DARIAH-ERIC/dariah-campus#569]
### Title of the resource

Building and Linking Humanities' Digital Spatial Infrastructures for Research

### Resource type

Captured Event

### Authors, editors and contributors

Marcus Smith, Ruth Mostern, Leif Isaksen, Alexandra Petrulevich, Sara Ellis Nilsson

### Topics (keywords)

Research infrastructures, Spatial humanities, Data modeling, Metadata, Geotagging, Controlled vocabularies, DH, Ontologies, Spatial research infrastructures, Semantic web, Linked open data, RDF

### Learning outcomes

Three recorded keynote lectures from the workshop Spatial data medieval to modern held in Uppsala May 30 - 1 June 2022. We have one to two associated blog posts that can be linked to as well.

### Abstract

The keynote lectures were produced as outputs from the workshop Spatial data medieval to modern held in Uppsala May 30 - 1 June 2022. The lectures cover key concepts in the field of (spatial) digital research infrastructures in the Humanities such as spatial infrastructures, LOD, metadata, ontology etc., outline major challenges in the field and give some concrete, authentic examples of how to overcome at least some of them in small- and large-scale projects in both academia and the GLAM sector. Lecture 1 Keeping a Sense of Perspective: Spatial Data Infrastructure and the Humanities by Leif Isaksen; Lecture 2 Linked Open Cultural Heritage Data: LOD and RDF in theory and practice by Marcus Smith; Lecture 3 The World Historical Gazetteer: Common metadata principles and common vocabulaties and ontologies by Ruth Mostern.

**Comment by VickyGarnett** [comment]
Resource published - closing issue
