### ISSUE TITLE
PDF downloads don't work in Events

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#617]
### Bug report

@stefanprobst, @VickyGarnett is preparing to publish another event and we just realized that our pdf downloads don't work anymore. 

If you go to our original event https://campus.dariah.eu/resource/events/open-data-citation-for-social-science-and-humanities and try to download the full synthesis, the link: https://campus.dariah.eu/resource/events/downloads/DARIAH_Winter_School-FullSynthesis.pdf will not work —  it will try to get something from downloads/DARIAH_Winter_School-FullSynthesis.pdf.html

Could you please look into this as soon as you can? Many thanks in advance.

**Comment by ttasovac** [comment]
addition:
pdfs from individual sessions seem to work.  https://campus.dariah.eu/_next/static/asset/content/events/open-data-citation-for-social-science-and-humanities/downloads/ac9b47cd627a2a60aba2575dd616bd04.pdf

but the full synthesis link doesn't.

**Comment by stefanprobst** [comment]
thanks for reporting! should be fixed.
