### ISSUE TITLE
Warning re experimental functions when fetching and pushing

### ISSUE THREAD

**Issue by VickyGarnett** [DARIAH-ERIC/dariah-campus#620]
### Bug report

Hi both,  just wanted to flag that I'm getting this grey pop up warning when I hit the 'push to origin' button.  It doesn't seem to be stopping me from completing this action, but I wanted to flag it in case it might be the cause of some of my current or future issues!!

<img width="1280" alt="Screenshot 2022-10-12 at 17 05 53" src="https://user-images.githubusercontent.com/57193002/195394089-b0aa2d28-d3c1-47af-8db2-73086f8e328f.png">

**Comment by stefanprobst** [comment]
this is fine and expected - it is coming from the fact that we have enabled an experimental next.js feature [here](https://github.com/DARIAH-ERIC/dariah-campus/blob/main/next.config.js#L15-L17)

**Comment by VickyGarnett** [comment]
OK, cool beans.  Thanks Stefan :) - V
