### ISSUE TITLE
Why is my editorial workflow empty?

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#644]
### Bug report

Hi Stefan. 

A colleague from ELEXIS submitted some changes to a resource via the CMS, I can see her pull request on GitHub (https://github.com/DARIAH-ERIC/dariah-campus/pull/643) but it's not showing up in my Workflow page in the CMS.

In fact, my Workflow is empty with the exception of one Person edit from July (https://github.com/DARIAH-ERIC/dariah-campus/pull/522).

So, two questions:

@VickyGarnett Can you please check the PR about Salvador and delete it if we don't need it, I'm pretty sure we already have Slavador as an author

@stefanprobst Why am I not seeing neither https://github.com/DARIAH-ERIC/dariah-campus/pull/522 in the CMS nor any other PRs. I logged in by going to campus.dariah.eu/admin

**Comment by stefanprobst** [comment]
the one you see is the only one from a contributor with admin permissions (vicky).

with "open authoring" enabled, any prs from external contributors (i.e. coming from a fork), must be managed and merged via the github ui.

see https://www.netlifycms.org/docs/open-authoring/#usage

**Comment by ttasovac** [comment]
yup, makes sense. thanks @stefanprobst 

@vicky, once you take care of the old PR, you can close this issue.
