### ISSUE TITLE
[new resource]: TRIPLE event Use of vocabularies for metadata curation and quality assessment in Social Sciences and Humanities

### ISSUE THREAD

**Issue by mr43** [DARIAH-ERIC/dariah-campus#677]
### Title of the resource

Use of vocabularies for metadata curation and quality assessment in Social Sciences and Humanities

### Resource type

Captured Event

### Authors, editors and contributors

Laure Barbot, Marco Raciti, Matej Durco, Daan Broeder, Cesare Concordia, Julien Homo, Tomasz Umerle, Antoine Isaac, Ceri Binding, Klaus Illmayer, Alessia Bardi, Nina Rastinger, Massimiliano Carloni 

### Topics (keywords)

Controlled Vocabularies, Semantic Web, DH, Information Architecture

### Abstract

This event, organised and provided by the TRIPLE project, aims at providing insights into the use of “topical vocabularies” and their use in metadata curation and quality assessment in the Social Sciences and Humanities (in the EOSC context). Thanks to this high-level training session, participants will have a better understanding of the interoperability challenges faced within/by the SSH branch of the EOSC, and be familiar with some initiatives related to metadata curation and enrichment in the SSH.

**Comment by VickyGarnett** [comment]
closing as resource published
