### ISSUE TITLE
[new resource]: Performing Arts: Transitioning to the Digital Age

### ISSUE THREAD

**Issue by azugic** [DARIAH-ERIC/dariah-campus#692]
### Title of the resource

Performing Arts: Transitioning to the Digital Age

### Resource type

Captured Event

### Authors, editors and contributors

Anamarija Žugić Borić, Antonia Hladilo Duspara, Koraljka Kuzman Šlogar

### Topics (keywords)

data management, data modeling, digital archives, metadata, repositories & collections, sound studies, performing arts

### Learning outcomes

By viewing this conference and the pre-conference workshop, learners will be able to:

- understand the objectives of the WG Theatralia project Performing Arts: Transitioning to the Digital Age
- expand their knowledge of international projects dedicated to the implementation of digital technologies in three perspectives of performing arts: scholarly research, artistic practices and archival processes.

### Abstract

This resource is based on the materials from the international conference "Performing Arts: Transitioning to the Digital Age", which was a part of the DARIAH-EU WG Theatralia project of the same name. The conference aimed to examine the possibilities of connecting information sciences and computer science with performing arts, focusing on three thematic blocks: archiving, artistic practices and scholarly research.

**Comment by azugic** [comment]
I am preparing one more (hosted) resource with the tag "performing arts", so please consider adding it to the list.

**Comment by azugic** [comment]
P. S. My abstract consists of 60 words, but I see some others are up to 80 words long. Please let me know if it should be shortened.

**Comment by VickyGarnett** [comment]
Hi Anamarija - the authors are now in the system, so you can make a start on the CMS now.

The abstract is fine at 60 words.  Would you be able to make the learning outcomes a bit more specific though?  You can have a few more learning outcomes if it helps to make it more specific.

Regarding the new tag: 'Performing Arts' - how many new resources do you anticipate creating that will use this? 

Thanks!

Vicky

**Comment by azugic** [comment]
Dear Vicky,

Thank you for your prompt answer!

Here are three more outcomes, I hope it's clearer now.
- gain insight into how using digital tools in performance can transform the experience of theatre
- understand the basic challenges of developing online archive resources for performing arts
- understand how digital theatre studies can cross methods with cognitive science

If there is too much text now, maybe that second, old entry can be dropped: - expand their knowledge of international projects dedicated to the implementation of digital technologies in three perspectives of performing arts: scholarly research, artistic practices and archival processes.

I am working on another resource using the performing arts tag, so it's two resources for now, but I'm sure that in the future we will add more resources as part of WG Theatralia projects. Also, I think the tag performing arts could be the umbrella term for many resources related to arts in general and could be very useful for future collaborators on the DARIAH-Campus platform.

Best
Anamarija

**Comment by VickyGarnett** [comment]
Hi Anamarija,

Thanks, I think those learning outcomes help to clarify what's in the resource.

I was already most of the way convinced about adding 'performing arts' as a tag, so if you think it's highly likely there will be more coming from your working group, I can add it.  Could you give me a short (c.20 words) description of what 'performing arts' is for the tag (I mean, obviously I know what performing arts is, but you are the expert in this so you will know which keywords to include!)

Thanks

V

**Comment by azugic** [comment]
No problem! Would this work? Feel free to modify it as you think it's better.

Performing Arts with reference to Digital Humanities mostly focuses on the use of digital tools in the study, creation and archiving of various materials and performances within theatre, dance, music and related arts.

**Comment by VickyGarnett** [comment]
Perfect!  Thanks Anamarija, I'll add that tag now :)

**Comment by azugic** [comment]
Dear Vicky,

By inserting content into the CMS, we noticed that we should have included all speakers in the proposal (not only the authors of the resource i.e. event), since they have to be inserted into the layout from the drop-down menu. I'm wondering if it's possible for me to attach a list of speakers (20 of them) now so you can insert them. Or even better we can create 20 new entries in ‘People’ list and mark them as ‘In review’. 

Also, I see that if I choose one of the offered authors from the drop-down menu as a test I still do not see the speaker box with biography in the preview on the right how it should look when published, so I'm curious if that is normal or if It will appear in the layout at the end. We are using this resource as a reference: [https://campus.dariah.eu/resource/events/building-and-linking-humanities-digital-spatial-infrastructures-for-research-in-the-nordic-countries](url)

Best,
Anamarija

**Comment by VickyGarnett** [comment]
Hi AnaMarija,

To address your last point first, yes unfortunately we are having a problem at the moment where speaker biogs aren't showing up for authors in event pages.  I've raised this, but will raise it again.

Regarding additional speakers, we can do this either of the ways you suggest.  If you want to create new speakers and create new pull requests, we can do that, or alternatively you can send me the list and I'll create them.  At this stage, it's perhaps quicker if you create them and I can merge them, but if you are tight for time yourself I am happy to add them for you.  Just let me know which way you'd like to do this so I can keep an eye out in the appropriate place.

Thanks

Vicky
________________________________

**Comment by azugic** [comment]
Dear Vicky,

thank you for a quick reply. I can create new speakers in 'People' list with biographies in the description box because we already have those prepared and I will mark them 'In review' for your verification. Also hopefully the problem with speakers showing up at the end will be resolved.

Best,
Anamarija

**Comment by VickyGarnett** [comment]
Great, thanks Anamarija, I'll keep an eye out for a GitHub notice in that case.

Thanks

Vicky
________________________________

**Comment by azugic** [comment]
Dear Vicky,

The event "Performing Arts: Transitioning to the Digital Age" is now finished and in review. Is there a possibility for you to approve it until 8 June so I can present it at the DARIAH Annual Event?

P. S. I am still waiting for the materials for the second resource I plan to propose.

Best
Anamarija
