### ISSUE TITLE
[new resource]: 

### ISSUE THREAD

**Issue by knielbo** [DARIAH-ERIC/dariah-campus#704]
### Title of the resource

Artificial Intelligence for the Humanities

### Resource type

External Resource

### Authors, editors and contributors

Stephan Smuts, Rebekah Baglini, Ross Deans Kristensen-McLachlan, Kristoffer Nielbo

### Topics (keywords)

Artificial Intelligence, AI, Deep Learning, Python

### Learning outcomes

_Knowledge_
* basic operational knowledge of Artificial Intelligence (AI).

_Skills_
* develop and manage deep learning workflows in Python

_Competences_
* competencies in creating domain adaptations of existing tools

### Abstract

Artificial Intelligence for the Humanities
=================

This course has been created to help anyone from the humanities (and beyond) to be able to use Artificial Intelligence (AI) in their work. It has been designed in such a way that those who work through it can use AI tools developed by the community with understanding of how they work. This is not a comprehensive course in AI, but rather a course that provides the quickest route from humanities to using AI tools in your own work. 

.. prereq::

   Basic knowledge of Python is necessary to follow this course.

.. toctree::
   :maxdepth: 1
   :caption: Lesson list

   lesson-1
   lesson-2
   lesson-3
   lesson-4
   lesson-5
   lesson-6
   useful-links
   case-study-posters
   case-study-entities

.. _learner-personas:

Who is the course for?
----------------------
The course is designed for anyone from the humanities, but people from other fields of study are also welcome.

About the course
----------------
Since the current academic and vocational landscape is largely based on using digital tools, it's becoming a necessity to understand how to use those digital tools. AI (which is an umbrella term for machine learning and deep learning) is extremely useful, but the learning curve to use and modify these tools is very steep. This course aims to reduce the steepness in that learning curve, so that these tools are available to those who could benefit from using them.

Case studies
------------
The course is in two parts: the lessons and the case studies. The lessons work like you would expect i.e. start at lesson 1 and work your way to the end. However, the case studies are there as examples and supplementary material which can help you understand the concepts better. When you have a problem that you are trying to solve, you can look at a case study that is similar to your problem. This can help you to understand how your own problem can be solved or give insights into possible ways in which it can be solved.

**Comment by VickyGarnett** [comment]
Hi @knielbo  - I've added the new people to the system now, so we should be all set for the NCC workshop.  In the meantime, it would be good to think about how to best phrase those learning outcomes so they can best finish the sentence "by the end of this course, learners will be able to.....".  I'd also like to add AI to the list of topics, so if you can think of a short sentence to best describe this topic (max 30 words), that would also be helpful.

Otherwise, we'll work on this in the NCC workshop and hopefully get it published there!

Thanks

Vicky

**Comment by knielbo** [comment]
i withdraw the proposal
