### ISSUE TITLE
CMS not publishing properly

### ISSUE THREAD

**Issue by VickyGarnett** [DARIAH-ERIC/dariah-campus#730]
### Bug report

Hi Stefan,

The CMS (using Google Chrome) is glitching pretty badly when trying to create new people.  it takes at least three or four attempts to get a person published.  Clicking on 'Save' can make the data in the form disappear, but not the entry itself.  Going back in to add that data again can see the same thing happen.  After about 2 or 3 more attempts going back in and out of the form, it finally sticks, and then I can move to changing the status from 'draft' to 'in review' to 'ready'.  But then it starts acting up again, and takes another few attempts to get it actually published.

Obviously as someone familiar with the system, I know to keep going.  But this is far from ideal.  For those who are not familiar, they might think they have done something wrong, and create a new profile, therefore creating multiple profiles for the same person.  Or they may think their work is done, and walk away without completing all the steps, and then later come back and wonder where their person's profile has gone.

From my point of view, it's quite frustrating because it takes at least 4 x as long to create a person's profile as it should do, and when I have a long list of 20 people, what should be a 25 minute job suddenly leaps up to 2 hours.

I'll email you a screen recording I've taken of these steps in action (the file is too big for this form!)

Cheers :)

V

**Comment by stefanprobst** [comment]
just tried creating a new person, and worked without issues. maybe this was a temporary glitch with the github api? is this still an issue for you?

**Comment by stefanprobst** [comment]
also - you can always create new people directly via git (which is probably quite a bit quicker for 20 entries)

**Comment by VickyGarnett** [comment]
HI @stefanprobst I've just added two new people on the CMS, and the glitching didn't happen at all.  So either you fixed something (thanks!) or it magicked itself back into working.  I'll keep an eye out for future glitching, but for now I think this particular issue is resolved. 
Thanks :D
