### ISSUE TITLE
Author profiles not appearing in Events

### ISSUE THREAD

**Issue by VickyGarnett** [DARIAH-ERIC/dariah-campus#735]
### Bug report

Hi Stefan,

I've had a few complaints from people now, and I've experienced this myself - the speaker profiles are not appearing in the Vercel previews when they are added to Captured events.  In theory these profiles should appear automatically when the speaker is added to a session.  I've checked and in all cases there are speaker biogs and images, so there isn't any information missing.

I'm afraid this one is fairly urgent as one of the contributors wanted to publish their event before the Annual Event in early June.

Thanks

Vicky

**Comment by stefanprobst** [comment]
can you link to an example which shows the issue?

**Comment by VickyGarnett** [comment]
I could.  But that's also a little tricky.  It's happening in my own event (PR#689) but that won't save properly so I can't give you a preview where I know for sure there should be authors there.  The alternative is Marco's TRIPLE event (PR#678) but that has a different problem where the preview keeps failing, so I can't show you that either! (I'll email you separately about that issue).

The alternative option is another event where someone has complained about not seeing the authors, but she hasn't created a pull request yet. :/

For info, this has happened on earlier events as well.  I was able to get around it by adding the 'speakers' section myself manually using markdown in GitHub, but that isn't working this time.

**Comment by ttasovac** [comment]
Hey @stefanprobst, I just looked at the error in Vercel for Vicky's resource #689 and it's the same as the error in #745:

`Error: Node.js version 16.x has reached End-of-Life. Deployments created on or after 2023-08-15 will fail to build. Please set "engines": { "node": "18.x" } in your `package.json` file to use Node.js 18.`


```

TypeError: Corrupt JPG, exceeded buffer limits
--
at validateBuffer (/vercel/path0/node_modules/image-size/dist/types/jpg.js:77:15)
at Object.calculate (/vercel/path0/node_modules/image-size/dist/types/jpg.js:101:13)
at lookup (/vercel/path0/node_modules/image-size/dist/index.js:43:53)
at Object.imageSize [as default] (/vercel/path0/node_modules/image-size/dist/index.js:118:16)
at /vercel/path0/src/cms/api/events.api.ts:355:32
at Generator.next (<anonymous>)
at fulfilled (/vercel/path0/src/cms/api/events.api.ts:24:58)
$ ts-node scripts/createRedirects
⛔ TypeError: Corrupt JPG, exceeded buffer limits
at validateBuffer (/vercel/path0/node_modules/image-size/dist/types/jpg.js:77:15)
at Object.calculate (/vercel/path0/node_modules/image-size/dist/types/jpg.js:101:13)
at lookup (/vercel/path0/node_modules/image-size/dist/index.js:43:53)
at Object.imageSize [as default] (/vercel/path0/node_modules/image-size/dist/index.js:118:16)
at /vercel/path0/src/cms/api/events.api.ts:355:32
at Generator.next (<anonymous>)
at fulfilled (/vercel/path0/src/cms/api/events.api.ts:24:58)

```

The first one we have until August to fix, but the second one, with "corrupted images" is weird because it's occurring now in multiple events that are being submitted and the error message is probably misleading because it can't be that everybody has corrupted images.

Vicky is now giving a workshop at the DARIAH Annual Event and some participants want to work on events. If you can take a look into this, that would be great... but of course if you're in the middle of something else, we'll understand.

**Comment by stefanprobst** [comment]
https://github.com/DARIAH-ERIC/dariah-campus/pull/689 now displays event session speaker info.

when manually editing mdx frontmatter, please ensure it is valid YAML (which is pretty picky wrt indentation)

**Comment by stefanprobst** [comment]
https://github.com/DARIAH-ERIC/dariah-campus/pull/678 now as well

**Comment by VickyGarnett** [comment]
> #689 now displays event session speaker info.
> 
> when manually editing mdx frontmatter, please ensure it is valid YAML (which is pretty picky wrt indentation)

Thanks for this Stefan.  Could you explain what you mean by 'valid YAML'?  Is that in the 'People' file you mean?  Were the biographies not right in there?  Or in the event index file?  In both cases, these were all filled out using the CMS, so indentation, in theory, shouldn't have been an issue?  Cheers :)

**Comment by stefanprobst** [comment]
> Could you explain what you mean by 'valid YAML'?

i mean the metadata section at the top of .mdx files (which is in YAML format). specifically, i was referring to

> I was able to get around it by adding the 'speakers' section myself manually using markdown in GitHub

which, i think, resulted in https://github.com/DARIAH-ERIC/dariah-campus/pull/689/commits/6ce46507e575713ce1b8a9d7d7dc4adf0a4d46a0 which is invalid YAML.
