### ISSUE TITLE
Event template not saving

### ISSUE THREAD

**Issue by VickyGarnett** [DARIAH-ERIC/dariah-campus#736]
### Bug report

Hi Stefan,

Sorry, another bug.  Again, using Google Chrome.

In the Event template, I'm having a similar problem to when creating a new person profile in that the CMS isn't saving any changes I make.  I've taken a screengrab of the message I'm getting.

Thanks!

Vicky
<img width="1440" alt="Screenshot 2023-05-25 at 18 03 40" src="https://github.com/DARIAH-ERIC/dariah-campus/assets/57193002/e5b27c1f-325c-468d-9461-bdfa2f8f6e43">

**Comment by stefanprobst** [comment]
just tried saving a new event, and it worked without issues. maybe this was a temporary glitch with the github api? are you still seeing this issue?

**Comment by VickyGarnett** [comment]
Just tried again, and it's still coming up with that same error message (screengrab attached) :/

<img width="1440" alt="Screenshot 2023-05-30 at 10 16 34" src="https://github.com/DARIAH-ERIC/dariah-campus/assets/57193002/1739ce4d-8eb8-4e65-ab7c-96baa1ffdc3f">

**Comment by VickyGarnett** [comment]
Hi @stefanprobst  - I tried working on this event again today, and the exact same issue is coming up.  Could you take a look at this as this event has been sitting here for a while in need of action.  Thanks :)
