### ISSUE TITLE
Word Embeddings [new resource]: 

### ISSUE THREAD

**Issue by e-liasz** [DARIAH-ERIC/dariah-campus#755]
### Title of the resource

Word Embeddings

### Resource type

External Resource

### Authors, editors and contributors

Joseph Flanagan

### Topics (keywords)

Machine Learning

### Learning outcomes

- learning what word embeddings are and how they are created
- learning how word embeddings have been used in digital humanities over the years
- learning about the problems regarding the use of word embeddings and how to tread when dealing with them

### Abstract

The material pertains to the theory and practicalities of using word embeddings in digital humanities. It first explains what word embeddings are and how they can be understood. Then, it puts that new knowledge into the perspective of digital humanities and how word embeddings have been used in this particular field.

**Comment by VickyGarnett** [comment]
Hi @e-liasz Joseph Flanagan is in the system now, so you can make a start drafting up your resource :)

**Comment by VickyGarnett** [comment]
resource published, closing issue
