### ISSUE TITLE
[new resource]: Introduction to programming for NLP with Python

### ISSUE THREAD

**Issue by kdesmedt** [DARIAH-ERIC/dariah-campus#766]
### Title of the resource

Introduction to programming for NLP with Python

### Resource type

External Resource

### Authors, editors and contributors

Koenraad De Smedt

### Topics (keywords)

programming, NLP, Python

### Learning outcomes

- explain simple Python programs for text and data processing
- write clear, valid Python programs for simple text and data processing
- break down a programming problem in smaller steps

### Abstract

The aim of this virtual course is to offer basic knowledge and skills in programming in Python. Target audiences are undergraduate and graduate students in the Humanities and Social Sciences who want to acquire hands-on knowledge and skills in working with language data. No previous programming experience is required, but some elementary knowledge and skills in the practical use of your computer, keyboard, web browser and file system, as well as some basal knowledge of linguistics and mathematics, are presupposed.

The core of the course consists of a series of Jupyter notebooks that combine examples of Python code with explanatory text. The notebooks provide demonstrations of simple language processing and the aggregation and visualization of qualitative and quantitative data, including data from real language research, from [CLARINO](https://clarino.uib.no/), and from other sources. They also suggest exercises which should solvable on the basis of the given examples and explanations. Ideally, the course should be presented by a teacher and the exercises should be supervised, but the modules are also suitable for self-study.

**Comment by kdesmedt** [comment]
https://mitt.uib.no/courses/38115/

**Comment by VickyGarnett** [comment]
Hi Koenraad - I've added you to the author's list on the system now, so you can make a start on drafting this up as an external resource now.

Thanks!  V

**Comment by kdesmedt** [comment]
Hi Vicky,

I have drafted the course up as a new resource. However, I have two issues:
 - It does not seem possible to add new tags. I need: Programming, NLP, Python.
 - It does not seem possible to add a new target group. I need: Students

I hope you can fix this, otherwise these items in the entry do not make much sense.

Best,
Koenraad

On 18 Jul 2023, at 11:40, VickyGarnett ***@***.***> wrote:



Hi Koenraad - I've added you to the author's list on the system now, so you can make a start on drafting this up as an external resource now.

Thanks! V

**Comment by kdesmedt** [comment]
I have drafted the course up as a new resource. However, I have two issues:
 - It does not seem possible to add new tags. I need: Programming, NLP, Python.
 - It does not seem possible to add a new target group. I need: Students

**Comment by kdesmedt** [comment]
Target groups should not be mutually exclusive.

**Comment by VickyGarnett** [comment]
Hi Koenraad,

I'll address the last point first - we don't deferentiate between students, academics, lifelong learners etc.  They all fall under the 'Domain Researchers' category.  Audience types have been broken into these 4 broad categories that address the needs of all our users, including practitioners and technical managers.  If we were to divide by more specific audience types we'd have far more than would be meaningful, so we kept it to four broad audience types.  It makes no real material difference to how the resources are displayed, so you rest assured that your resource will be found by the right people.

As for the tags, we can look into adding something there.  I think there is justification for adding all three.  Perhaps you could help here by providing a brief one-sentence description of each, and then I can add them to the system for you.

Thanks :)

Vicky

**Comment by kdesmedt** [comment]
The tags are quite self-explanatory.
Programming: Writing computer instructions.
NLP or Natural Language Processing: Processing of natural language by a computer.
Python: Widely used computer language conceived by Guido van Rossum

**Comment by VickyGarnett** [comment]
Hi Koenraad - just checking in to see how you're getting on with this resource?  I've added 'Natural Language Processing' and 'Python' as tags now for you, although on reflection I thought perhaps 'programming' might be a bit too broad a tag at this point.  If you feel it's absolutely necessary and want to persuade me otherwise, I'm open to discussion though.

Let me know if you need any further help.

Thanks

Vicky

**Comment by kdesmedt** [comment]
Fine with me.

**Comment by VickyGarnett** [comment]
Great, OK, well whenever you're ready to send it on, assuming you're using the CMS, you can save it, and change the status to 'In Review' and I will get a notice that it's there.  Thanks :) V

**Comment by kdesmedt** [comment]
I had saved a draft of the course in the CMS, but now I can't find it. Do you have the link?

**Comment by kdesmedt** [comment]
Ah, now I just found it in the byzantine CMS. But I can't add the tags that you defined.

**Comment by VickyGarnett** [comment]
Well, if you want to send it over 'to review' I can add those tags for you and generate a full preview so you can take a look at it.  To be clear, it won't be published until we agree on it, so you (or I) can make changes to it if needs be.

**Comment by kdesmedt** [comment]
OK, sent to review.

**Comment by kdesmedt** [comment]
I see the tags are added now. Seems good.

**Comment by VickyGarnett** [comment]
resource published, closing issue
