### ISSUE TITLE
[new resource]: Foundations of AI

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#784]
### Title of the resource

Foundations of AI

### Resource type

Hosted Resource

### Authors, editors and contributors

Emily Genatowski

### Topics (keywords)

AI, Large Language Models

### Learning outcomes

Students will understand the history and progression of AI, types of AI and its various interfaces.

### Abstract

This resource will cover the history and progression of AI from its origins to the major developmental milestones.  A general overview of how AI works, the three major categories of AI algorithms: supervised learning, unsupervised learning, and reinforcement learning, the types of AI, the forms of training data sets, the types of interfaces and the input-output formats. The types of AI being used, their strengths and weaknesses and how they differ. This class will include Machine Learning, Deep Learning, Natural Language Processing, Computer Vision and Robotics. Particular attention will be paid to NLP and its basis of Large Language Models in order to set the foundation for upcoming discussions. The various interfaces AI can provide the basis for including chatbots, image recognition, video analysis, voice assistants, virtual and augmented reality, gesture and motion recognition and brain computer interfaces. The current tools on the market which provide interaction with AI in each format will be introduced and demonstrated in real time.

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - I've put Emily Genatowski into the system now, so you can make a start drafting up the resource on the CMS now: https://campus.dariah.eu/docs/using-the-content-management-system

**Comment by emilykateemilykate** [comment]
Thank you so much, Vicky! I'm so excited to begin building!

**Comment by emilykateemilykate** [comment]
This resource is no longer in development.
