### ISSUE TITLE
[new resource]: Ethical, Societal and Legal Complexities of AI

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#785]
### Title of the resource

Ethical, Societal and Legal Complexities of AI

### Resource type

Hosted Resource

### Authors, editors and contributors

Emily Genatowski

### Topics (keywords)

AI, Large Language Models

### Learning outcomes

Students will learn about the complexities of the rapid growth, development and implementation of AI.

### Abstract

This resource will cover ethical Issues including bias, privacy, accountability, transparency, security threats and autonomy.  There will be an overview of the issues, examples of ethical issues pertaining to each point above, technical misuse that may lead to those issues and methods of regulation or guidance that could be implemented in order to mitigate the adverse ethical effects. Then it will cover Legal Issues including liability, intellectual property, data protection and privacy, discrimination and regulation.  Overview of the issues, examples of each of the above, misuse that may lead to those issues and methods of regulation or laws that could be implemented in order to mitigate the legal issues stemming from the use of AI. Then it will cover societal Issues including employment, job displacement, surveillance, safety, autonomy, security and dehumanization. Overview of the issues, examples of issues above, systemic misuse that may lead to those issues and proposed regulation or guidance that could be implemented in order to mitigate the adverse societal effects.

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - thanks for all the work on this.  I've now published the resource after a making a few minor edits to the Learning Outcomes and adding the 'AI' tag for you.  I'll close this issue as well, but you can view the published resource here: https://campus.dariah.eu/resource/posts/ethical-societal-and-legal-complexities-of-ai

Cheers!

V
