### ISSUE TITLE
[new resource]: Real World Applications of AI

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#786]
### Title of the resource

Real World Applications of AI 

### Resource type

Hosted Resource

### Authors, editors and contributors

Emily Genatowski

### Topics (keywords)

AI, Large Language Models

### Learning outcomes

Students will understand the real world applications of AI and learn how they might apply AI to other fields as well.

### Abstract

This resource will cover current applications of AI in the fields of Healthcare, Finance, Education, Agriculture, Transportation, Entertainment, Marketing, Security and Environmental Science.  The benefits and specific drawbacks as well as the current limitations and potential expected future use in each field and what is blocking the immediate implementation.

**Comment by VickyGarnett** [comment]
Thanks Emily.  You're already in the system, so you can begin drafting this resource up on the CMS now.  We don't have LLMs as a tag, currently, but if you have more than one resource that requires it, we can look at adding that one as well. - V
