### ISSUE TITLE
[new resource]: Text to Text Prompt Engineering Intensive

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#787]
### Title of the resource

Text to Text Prompt Engineering Intensive

### Resource type

Hosted Resource

### Authors, editors and contributors

Emily Genatowski

### Topics (keywords)

AI, Large Language Models

### Learning outcomes

Students will learn prompt engineering techniques and methods to apply to AI text to text LLM.

### Abstract

Methods such as conditional logic, tokenization, prompt libraries, pre-processing, domain-specific language, syntactic cues, parallel prompts, intentional branching, identity assignation, and multi-turn refinement will be introduced, explained and modeled during this resource.

**Comment by VickyGarnett** [comment]
Hi Emily, you can proceed to draft this resource up now.

If you want to add Large Language Models, perhaps you could propose a definition for them. 

Cheers

V
