### ISSUE TITLE
[new resource]: Text to Image Prompt Engineering Intensive

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#788]
### Title of the resource

Text to Image Prompt Engineering Intensive

### Resource type

Hosted Resource

### Authors, editors and contributors

Emily Genatowski

### Topics (keywords)

AI, Large Language Models

### Learning outcomes

Students will learn how to apply the techniques covered in this resource towards engineering prompts for use with text to image AI models.

### Abstract

Methods such as word weighting, dataset informed reference cues, sensorial language, limitation and constraint boundary assignment, environmental, character, object, temporal, atmospheric and movement descriptors, and compositional terminology will be introduced, explained and modeled during the resource.

**Comment by VickyGarnett** [comment]
Hi Emily, you can proceed to draft this resource on the CMS now.  Thanks V
