### ISSUE TITLE
[new resource]: Text to Video Prompt Engineering Intensive

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#789]
### Title of the resource

Text to Video Prompt Engineering Intensive

### Resource type

None

### Authors, editors and contributors

Emily Genatowski

### Topics (keywords)

AI, Large Language Models

### Learning outcomes

Students will learn when and how to incorporate these specific prompt engineering techniques to text to video LLMs.

### Abstract

Methods such as temporal guidance, textual storyboarding, active voice, dialogue vs scenic input, visual styling and media reference, prompt tone cues, concrete descriptors, word weighting, sequencing cues and cinematic framing terminology will be introduced, explained and modeled during the resource.

**Comment by VickyGarnett** [comment]
Hi Emily, you can proceed to draft this resource up on the CMS now - cheers V
