### ISSUE TITLE
Urgent fix requested for my requested updates to save

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#803]
### Bug report

Greetings team!  I made a ton of the suggested changes to my Ethical, Societal and Legal Complexities of Aritificial Intelligence resource and went to save my progress and I got an error message reading: failure to persist entry: cannot read properties of undefined (reading: sha). I think it may be because it’s already live.  Perhaps there is a work around we can use? I remain at the ready to work through the changes all day/night today. @ttasovac @VickyGarnett

**Comment by ttasovac** [comment]
Usually when things go wrong, there is a formatting issue with the underlying Markdown. I assume this error is making it impossible for you to save, i.e. commit anything? If so, the difficulty on our end is that we can't really see what you're trying to save. Let's see if @stefanprobst can suggest some magic.

Stefan, just so you know, this is fairly time-sensitive —  there is a workshop in Vienna tomorrow that we need this resource for.  @vronk is in the loop.

**Comment by stefanprobst** [comment]
what PR is this refering to?

**Comment by ttasovac** [comment]
unfortunately, this resource is already published, so these are additional changes... and I'm not sure @emilykateemilykate could commit anything. Emily, can you confirm?

**Comment by stefanprobst** [comment]
if you send me the updated markdown content i can integrate the changes manually

otherwise, editing a published entry via cms should work (?):

- sign in to the cms
- in collections > resources find the entry with "Ethical, Societal and Legal Complexities of Artificial Intelligence" and click on it
- edit and save your changes

**Comment by emilykateemilykate** [comment]
Okay, on the tab where I made the changes, they will not save but I opened
a new tab and logged in again and made some test changes and they seem to
save.  I'll convert them one by one to the new tab.  Thank you for your
help!

**Comment by VickyGarnett** [comment]
Closing this issue as the resource is published
