### ISSUE TITLE
[new resource]: From the shelf to the web, exploring historical newspapers in the digital age

### ISSUE THREAD

**Issue by spapastamkou** [DARIAH-ERIC/dariah-campus#836]
### Title of the resource

From the shelf to the web, exploring historical newspapers in the digital age

### Resource type

External Resource

### Authors, editors and contributors

Marten Düring, Estelle Bunout, Stefania Scagliola

### Topics (keywords)

Digital Source Criticism, DH

### Learning outcomes

* understand how digital technologies (optical character recognition - OCR, article segmentation) have impacted the way we can access newspapers as historical sources
* understand how an online search environment works 
* get acquainted with searching the database and apply source criticism

### Abstract

The lesson deals with how digitised newspapers that are available online change the way historians use newspapers as historical sources, and ask new skills for applying source criticism.

**Comment by spapastamkou** [comment]
This is a resource coming from Ranke.2 and available at: https://ranke2.uni.lu/u/exploring-historical-newspapers/
Thank you.

**Comment by VickyGarnett** [comment]
Hi @spapastamkou  - apologies for the delay in responding to this.  All those authors are already in the system, so I'm happy for you to proceed with drafting up this resource on the CMS :)

**Comment by spapastamkou** [comment]
Dear @VickyGarnett, finally I created the draft for the lesson "From the shelf to the web, exploring historical newspapers in the digital age". 
There is one point I would like us to clarify together: I was not able to find the name of "Stefania Scagliola" in the list of entries when I tried to register her as editor of the lesson. (She was not in the authors list either). Normally she exists as she is already on two other lessons of Dariah Campus. Can you help me please with this? Stefania is to appear as editor for this lesson. 
Additionally, I did not upload the image of the lesson, which is optional anyway. I will ask my colleagues to help me locate the file and hope I can attach it soon. cc @frederic-reis

Thanks a lot!

**Comment by spapastamkou** [comment]
@VickyGarnett I attach here the URL of the image of the lesson: https://impresso.github.io/assets/images/project-schema.jpg (free of restrictive rights of use). Thanks!

**Comment by VickyGarnett** [comment]
> Dear @VickyGarnett, finally I created the draft for the lesson "From the shelf to the web, exploring historical newspapers in the digital age". There is one point I would like us to clarify together: I was not able to find the name of "Stefania Scagliola" in the list of entries when I tried to register her as editor of the lesson. (She was not in the authors list either). Normally she exists as she is already on two other lessons of Dariah Campus. Can you help me please with this? Stefania is to appear as editor for this lesson. Additionally, I did not upload the image of the lesson, which is optional anyway. I will ask my colleagues to help me locate the file and hope I can attach it soon. cc @frederic-reis
> 
> Thanks a lot!

Hi Sofia,

Good to hear you're on top of things!

Odd that Stefania didn't show up when you went to search for her name.  She's definitely in the system.  Sometimes is easier to search if you just type in a few letters, so you could start by just searching for 'stef' and seeing if that works.

You should be able to add that image yourself using the CMS.  A pop-up window will appear giving you the option to upload media.

Once you have it ready to go, you should make sure you save it and change the status to 'in review'.  That will push it through to me in the main repository and I can review it then.

Thanks!

Vicky

**Comment by spapastamkou** [comment]
Thanks @VickyGarnett - I believe everything is fixed now: image and Stefania are in, and status changed to 'in review'. Let me know in case you need further actions from me. Thanks a lot!

**Comment by VickyGarnett** [comment]
Associated resource published, closing this issue :)
