### ISSUE TITLE
[new resource]: Finding Places in Text with the World Historical Gazetteer

### ISSUE THREAD

**Issue by anisa-hawes** [DARIAH-ERIC/dariah-campus#879]
### Title of the resource

Finding Places in Text with the World Historical Gazetteer

### Resource type

External Resource

### Authors, editors and contributors

Susan Grunewald, Andrew Janco, Anna-Maria Sichani, Eleni Gadolou, Randa El Khatib

### Topics (keywords)

DH, Open access, Open education, Natural Language Processing

### Learning outcomes

Readers will discover:

- How to programmatically search documents for a list of terms, including place names
- How to produce a tab-separated value (TSV) file where each row gives the matched term and the term's location in the text
- How to generate a visualization that can be used to interpret the matches in context
- How to combine text analysis with mapping

### Abstract

Researchers often need to be able to search a corpus of texts for a defined list of terms and historians are often interested in certain places named in a text or texts. This lesson details how to programmatically search documents for a list of terms, including place names and then how to obtain coordinates and map historical place names with the World Historical Gazetteer.

**Comment by VickyGarnett** [comment]
Hi Anisa,

The authors for this resource are now in the CMS - you can proceed to drafting this resource up, and as discussed you can follow the steps in the documentation, which you can find here: https://campus.dariah.eu/docs/using-the-content-management-system

Thanks

Vicky

**Comment by VickyGarnett** [comment]
Closing as resource published
