### ISSUE TITLE
[new resource]: Displaying a Georeferenced Map in KnightLab’s StoryMap JS

### ISSUE THREAD

**Issue by anisa-hawes** [DARIAH-ERIC/dariah-campus#880]
### Title of the resource

Displaying a Georeferenced Map in KnightLab’s StoryMap JS

### Resource type

External Resource

### Authors, editors and contributors

Erica Y. Hayes, Mia Partlow, Alex Wermer-Colan, Lorena Gauthereau, Emma Slayton

### Topics (keywords)

DH, Open access, Open education, Spatial humanities

### Learning outcomes

Learners will discover:

- How to customize and share a georeferenced map online using StoryMap JS, an interactive web-based mapping platform
- How to integrate historical and contemporary maps into interactive stories

### Abstract

In this lesson, you will learn how to display a georeferenced map from Map Warper in KnightLab’s StoryMap JS, an interactive web-based map and storytelling platform.

**Comment by VickyGarnett** [comment]
Hi Anisa - the authors for this resource have been added to the CMS.  You can now proceed to draft this resource up.

Thanks

Vicky

**Comment by VickyGarnett** [comment]
Resource published, closing issue :)
