### ISSUE TITLE
[new resource]: Regression Analysis with Scikit-learn (part 2 - Logistic)

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#881]
### Title of the resource

Regression Analysis with Scikit-learn (part 2 - Logistic)

### Resource type

External Resource

### Authors, editors and contributors

Matthew J. Lavin, James Baker, Thomas Jurczyk, Rennie C Mapp

### Topics (keywords)

DH, Open Education, Open Access, data visualisation

### Learning outcomes

After completing this lesson, you will have learned:
1. How to run logistic regression algorithms in Python using the Scikit-learn library
2. How to validate models and assess their performance
3. How to interpret the results given by logistic regression models
4. To know which common pitfalls to avoid when conducting regression analysis

### Abstract

This lesson is the second in a two-part lesson focusing on regression analysis. It provides an overview of logistic regression, how to use Python (Scikit-learn) to make a logistic regression model, and a discussion of interpreting the results of such analysis.

**Comment by VickyGarnett** [comment]
Hello Charlotte - the authors of this resource have been added to the CMS, and you can now proceed to drafting this up.
Thanks

Vicky

**Comment by VickyGarnett** [comment]
Closing issue as resource published :)
