### ISSUE TITLE
[new resource]: Regression Analysis with Scikit-Learn (part 1 - Linear)

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#882]
### Title of the resource

Regression Analysis with Scikit-Learn (part 1 - Linear)

### Resource type

External Resource

### Authors, editors and contributors

Matthew J. Lavin, James Baker, Thomas Jurczyk, Rennie C Mapp

### Topics (keywords)

DH, Open Education, Open Access, data visualisation

### Learning outcomes

After completing this lesson, you will have learned:
1. How to run linear regression algorithms in Python using the Scikit-learn library
2. How to validate models and assess their performance
3. How to interpret the results given by linear regression models
4. To know which common pitfalls to avoid when conducting regression analysis

### Abstract

This lesson is the first of a two-part lesson focusing on an indispensable set of data analysis methods, logistic and linear regression. It provides an overview of linear regression and walks through running both algorithms in Python (using Scikit-learn). The lesson also discusses interpreting the results of a regression model and some common pitfalls to avoid.

**Comment by VickyGarnett** [comment]
These authors are now in the system, so you can proceed to drafting it in the CMS

Thanks - Vicky :)

**Comment by VickyGarnett** [comment]
Closing issue as resource published :)
