### ISSUE TITLE
[new resource]: Computer Vision for the Humanities: An Introduction to Deep Learning for Image Classification (Part 2)

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#883]
### Title of the resource

Computer Vision for the Humanities: An Introduction to Deep Learning for Image Classification (Part 2)

### Resource type

External Resource

### Authors, editors and contributors

Daniel van Strien, Kaspar Beelen, Melvin Wevers, Thomas Smits, Katherine McDonough, Nabeel Siddiqui, Alex Wermer-Colan, Michael Black, Catherine DeRose 

### Topics (keywords)

DH, Open Education, Open Access, Python, Machine learning

### Learning outcomes

After completing this lesson, you will have learned:
1. To interpret what different metrics mean about your model's performance, and to identify where it is performing poorly
2.  To use data augmentation as a tool for reducing the amount of training data needed to train a machine learning model.
3. To understand the complexity of mapping complex or fuzzy concepts onto set categories

### Abstract

This is the second of a two-part lesson introducing deep learning based computer vision methods for humanities research. This lesson digs deeper into the details of training a deep learning based computer vision model. It covers some challenges one may face due to the training data used and the importance of choosing an appropriate metric for your model. It presents some methods for evaluating the performance of a model.

**Comment by charlottejmc** [comment]
I've noticed an error in the `Authors, editors and contributors ` section. it should read instead:
```
Daniel van Strien, Kaspar Beelen, Melvin Wevers, Thomas Smits, Katherine McDonough, Nabeel Siddiqui, Alex Wermer-Colan, Michael Black, Catherine DeRose
```
Thank you!

**Comment by VickyGarnett** [comment]
Hi Charlotte - the authors for this resource are now all in the CMS, and you can proceed to drafting it up.

Thanks

Vicky

**Comment by VickyGarnett** [comment]
Closing issue as resource published :)
