### ISSUE TITLE
[new resource]: Computer Vision for the Humanities: An Introduction to Deep Learning for Image Classification (Part 1)

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#884]
### Title of the resource

Computer Vision for the Humanities: An Introduction to Deep Learning for Image Classification (Part 1)

### Resource type

External Resource

### Authors, editors and contributors

Daniel van Strien, Kaspar Beelen, Melvin Wevers, Thomas Smits, Katherine McDonough, Nabeel Siddiqui, Alex Wermer-Colan, Michael Black, Catherine DeRose

### Topics (keywords)

DH, Open Education, Open Access, Python, Machine learning

### Learning outcomes

After completing this lesson, you will have learned:
1. What steps are needed to train a deep learning model
3. To understand some of the specific considerations around using deep learning and computer vision for humanities research

### Abstract

This is the first of a two-part lesson introducing deep learning based computer vision methods for humanities research. Using a dataset of historical newspaper advertisements and the fastai Python library, the lesson walks through the pipeline of training a computer vision model to perform image classification.

**Comment by VickyGarnett** [comment]
Hi Charlotte - the authors for this resource are in the CMS now

Thanks

Vicky

**Comment by VickyGarnett** [comment]
Closing issue as resource published :)
