### ISSUE TITLE
[new resource]: Interrogating a National Narrative with GPT-2

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#885]
### Title of the resource

Interrogating a National Narrative with GPT-2

### Resource type

External Resource

### Authors, editors and contributors

Chantal Brousseau, Katie McDonough, Lorella Viola, John R. Ladd, Tiago Sousa Garcia

### Topics (keywords)

DH, Open Education, Open Access, Python, Machine learning

### Learning outcomes

After completing this lesson, you will be able to:
1. Apply (GPT-2) to a large-scale text corpus in order to produce automatically-written responses to prompts based on the contents of the corpora
2. Gain insight into common machine learning terminology and concepts which can be applied to other branches of machine learning
3. Understand the ethical complications of producing this form of research

### Abstract

In this lesson, you will learn how to apply a Generative Pre-trained Transformer language model to a large-scale corpus so that you can locate broad themes and trends within written text.

**Comment by VickyGarnett** [comment]
Hi @charlottejmc - can you let me know if 'Katie McDonough' is the same person as 'Katherine McDonough' from previous resources you've proposed here?  Just to make sure I don't create two profiles for the same person :)

Thanks

Vicky

**Comment by VickyGarnett** [comment]
Closing issue as resource now published :)
