### ISSUE TITLE
[new resource]: Scalable Reading of Structured Data

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#886]
### Title of the resource

Scalable Reading of Structured Data

### Resource type

External Resource

### Authors, editors and contributors

Max Odsbjerg Pedersen, Josephine Møller Jensen, Victor Harbo Johnston, Alexander Ulrich Thygesen, Helle Strandgaard Jensen

### Topics (keywords)

DH, Open Education, Open Access, data modeling

### Learning outcomes

After completing this lesson, you will be able to:

1. Set up a workflow where exploratory, distant reading is used as a context to guide the selection of individual data points for close reading
2. Employ exploratory analyses to find patterns in structured data
3. Apply and combine basic filtering and arranging functions in R

### Abstract

In this lesson, we introduce a workflow for scalable reading of structured data, combining close interpretation of individual data points and statistical analysis of the entire dataset. The lesson is structured in two parallel tracks:

- A general track, suggesting a way to work analytically with structured data where distant reading of a large dataset is used as context for a close reading of distinctive datapoints.
- An example track, in which we use simple functions in the programming language R to analyze Twitter data. 

Combining these two tracks, we show how scalable reading can be used to analyze a wide variety of structured data. Our suggested scalable reading workflow includes two distant reading approaches that will help researchers to explore and analyze overall features in large data sets (chronologically and in relation to binary structures), plus a way of using distant reading to select individual data points for close reading in a systematic and reproducible manner.

**Comment by VickyGarnett** [comment]
@charlottejmc - The authors for this resource are in the CMS, so you can proceed to drafting this resource up :) - V

**Comment by VickyGarnett** [comment]
closing as published
