### ISSUE TITLE
[new resource]: Making an Interactive Web Application with R and Shiny

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#887]
### Title of the resource

Making an Interactive Web Application with R and Shiny

### Resource type

External Resource

### Authors, editors and contributors

Yann Ryan, Alex Wermer-Colan, Amanda Regan, Nicole Lemire Garlic

### Topics (keywords)

DH, Open Education, Open Access, Data visualisation

### Learning outcomes

After completing this lesson, you will be able to:

1. Create a basic interactive Shiny application
2. Understand the key layouts and design principles of the Shiny UI
3. Use Shiny's 'reactive programming' to ‘listen’ for certain inputs, and understand how they are connected to outputs displayed in your app

### Abstract

This lesson demonstrates how to build a basic interactive web application using Shiny. Shiny is a library (a set of additional functions) for the programming language R. Its purpose is to facilitate the development of web applications, which allow a user to interact with R code using User Interface (UI) elements in a web browser, such as sliders, drop-down menus, and so forth. In the lesson, you will design and implement a simple application, consisting of a slider which allows a user to select a date range, which will then trigger some code in R, and display a set of corresponding points on an interactive map.

**Comment by VickyGarnett** [comment]
Hi Charlotte - The authors of this resource are now in the CMS, and you can proceed to drafting it up

Thanks

Vicky

**Comment by VickyGarnett** [comment]
resource published, closing issue
