### ISSUE TITLE
[new resource]: Introduction to Map Warper

### ISSUE THREAD

**Issue by charlottejmc** [DARIAH-ERIC/dariah-campus#888]
### Title of the resource

Introduction to Map Warper

### Resource type

External Resource

### Authors, editors and contributors

Anthony Picón Rodríguez, Miguel Cuadros, Lorena Gauthereau, Erica Hayes, Mia Partlow, Alex Wermer-Colan, Joshua G. Ortiz Baco, Adriana Cásarez

### Topics (keywords)

DH, Open Education, Open Access, Spatial humanities, Data visualisation

### Learning outcomes

After completing this lesson, you will be able to:

1. Align geographic coordinates to a scanned historical map
2. Export your georeferenced map to different formats
3. Understand the various considerations to keep in mind when choosing a historical map to georeference

### Abstract

This lesson introduces basic use of Map Warper for historical maps. It guides you from upload to export, demonstrating methods for georeferencing and producing visualizations.

**Comment by VickyGarnett** [comment]
Hi Charlotte - the authors for this resource are now all in the CMS, so you can carry on and draft it up

Thanks

Vicky

**Comment by VickyGarnett** [comment]
Closed as resource published
