### ISSUE TITLE
amend starting point for event sessions

### ISSUE THREAD

**Issue by VickyGarnett** [DARIAH-ERIC/dariah-campus#935]
### Bug report

Hi Stefan,

I noticed today that the URLs for individual sessions in the events don't match up with the session numbers on the screen.  For example, where a session URL ends 'session=4', this is actually for session 5.  I wonder could we start the counting point for these sessions at 1 rather than 0 to avoid confusion if people choose to share them.

Thanks

Vicky

**Comment by stefanprobst** [comment]
unfortunately we cannot simply change urls because users might have already bookmarked the current ones.

we should collect these breaking changes for the next iteration of DC.
