### ISSUE TITLE
slugs no longer working?

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#939]
### Bug report

I've tried to create a slug in #938, but this doesn't seem to do anything anymore. In the Vercel preview, the url is still the original one with the apostrophe. Can you please investigate?

**Comment by stefanprobst** [comment]
did we ever support a `slug` frontmatter field?

you can change a resource's url by changing the folder name, e.g. in #938 you would want to remove the apostrophe from the `content/posts/displaying-a-georeferenced-map-in-knightlab’s-storymap-js/index.mdx` folder.

when changing a resource url we should also add a redirect, so old bookmarks still work. i'll add a new `redirects.json` file for that.

**Comment by stefanprobst** [comment]
updated and merged #938 and added a redirect.
