### ISSUE TITLE
[new resource]: Prosopography: Prosopon

### ISSUE THREAD

**Issue by emilykateemilykate** [DARIAH-ERIC/dariah-campus#949]
### Title of the resource

Prosopography: What is a Prosopon?

### Resource type

Hosted Resource

### Authors, editors and contributors

Emily Genatowski

### Topics (keywords)

Prosopography, Digital Humanities

### Learning outcomes

The students will be able to tackle three main issues with prosopography by the end of the course: multiple people with the same name, anonymous entries and fictional people. 

### Abstract

A prosopon is a collected literary representation of a person. A common problem in prosopography is known as the Rusudan Problem whereby disambiguation is necessitated through a lack of information. This issue requires personalized standards and careful consideration. This resource will provide guidance on how to create and implement these standards.

**Comment by VickyGarnett** [comment]
Hi Emily Kate - How are you getting on with creating this resource and a pull request for it?
