### ISSUE TITLE
Linking Digital Heritage, Games and Virtual Tourism

### ISSUE THREAD

**Issue by EirikurSmariSigurdarson** [DARIAH-ERIC/dariah-campus#958]
### Title of the resource

Linking Digital Heritage, Games and Virtual Tourism

### Resource type

External Resource

### Authors, editors and contributors

Erik Champion

### Topics (keywords)

Augmented reality, Cultural heritage, Spatial humanities, 3D modelling, Game design, Research infrastructures

### Learning outcomes

A﻿fter studying the resource, learners should be able to:
- understand how 3D models and game design can be used for cultural heritage studies and learning;
- appreciate the challenges with maintaining 3D models and research data.

### Abstract

This talk examines how key challenges in digital heritage involving 3D models could be brought to life and re-opened to interpretation by game design, and how game-like interaction could also help increase the richness and immersive qualities of XR (extended reality) and virtual tourism. Can 3D models, the scholarly information surrounding them, and the involvement of the public be brought closer together? And can we harness the speed and complexity of new technologies to ensure both the data and our understanding of that data can be recorded, interpreted, and shared more fairly, openly, and democratically?

Link to resource: https://www.youtube.com/watch?v=MQKy_y1IE54&t=17s

Developed within the INTERREG NPA funded project DACCHE: https://linktr.ee/dacche_interreg

Event hosted by the Centre for Digital Humanities and Arts (https://www.mshl.is) and the Gunnar Gunnarsson Institute (https://www.skriduklaustur.is/is/gunnarsstofnun).

**Comment by VickyGarnett** [comment]
Hi @EirikurSmariSigurdarson - the author for this resource has now been added to the system so you can proceed to draft this up now.

Just a note - the information you have given in the 'Abstract' section looks great, but I think it will work better if this is given in the main content page.  For an abstract we will only need around 80 words and no links or URLs.

Thanks!

Vicky

**Comment by VickyGarnett** [comment]
Closed as resource published
