### ISSUE TITLE
adding aouthors give error TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by mashalahmad** [DARIAH-ERIC/dariah-campus#98]
Hi
I have been trying to ingest external resources for my organisation Digital repository of Ireland. Whenever I add authors it gives me the above type error when I preview the resource in local server. could you tell what Im doing wrong?

**Comment by ttasovac** [comment]
Can you please show me an example of exactly how you're adding authors and where.

**Comment by mashalahmad** [comment]
Im adding an external resource and here is the sample
---
title: Using Digital Archives for Historical Research
date: 2021-02-23
categories:
  -- parthenos
tags:
  -- e-heritage
  -- open-access
  -- training-education
abstract:
  This video recording is of 'Using Digital Archives for Historical Research', the first webinar in a three-part public lecture series hosted by the Digital Repository of Ireland (DRI) aimed at early career researchers. The webinar showcases the rich research resources contained in digital archival collections that can be used to advance historical research.
type: training module 
contributors:
  -ciarán-wallace
  -siobhán-doyle
  -tara-doyle
  -stephanie-rousseau
  -kevin-long
 authots:
 -- digital-repository-of-ireland 
remoteUrl: https://doi.org/10.7486/DRI.r4958772q
remotePublicationDate: 2021-02-23
---

This recording is of ‘Using Digital Archives for Historical Research’, the first webinar in a three-part public lecture series on using digital archives for academic research hosted by the Digital Repository of Ireland (DRI) and aimed primarily at early career researchers.

Access to brick-and-mortar archives has been limited due to COVID-19 restrictions, creating challenges for humanities researchers that rely on archival materials for their research. This webinar aims to showcase some of the rich research resources contained in digital archival collections.
 
Featured digital collections in the first webinar include:
 
- Beyond 2022: This archival initiative aims to restore – as far as possible – the collections lost in the destruction of the Public Record Office of Ireland in 1922, at the outbreak of the Irish Civil War.
- The Inspiring Ireland Project - National Museum of Ireland: This collection contains a selection of cultural heritage objects from the National Museum of Ireland presented as part of the Inspiring Ireland project, which features a series of exhibitions containing cultural artefacts related to the events of 1916.
- Bureau of Military History (1913-1921): The Bureau of Military History Collection, 1913-1921 (BMH) is a collection of 1,773 witness statements; 334 sets of contemporary documents; 42 sets of photographs, and 13 voice recordings that were collected by the State between 1947 and 1957, in order to gather primary source material for the revolutionary period in Ireland from 1913 to 1921.
- Dublin City Library and Archive (DCLA), Fáilte Ireland Tourism Photographic Collection
and Jacob's Biscuit Factory Archive: These collections, spanning from the 1890s to the early 2000s, comprise almost 20,00 images between them and growing.

After watching this webinar, early career researchers will be familiar with some of the digital archival collections that can be explored to advance historical research. 



<CTA
  title="Interested in learning more?"
  subtitle="Using Digital Archives for Historical Research"
  url="https://doi.org/10.7486/DRI.r4958772q"
/>


Funny thing is if I add authors copying from another already published resource than author shows up but in my case it crashes.
Kidnly consider -- as - otherwise github convert it into bullet point.

**Comment by ttasovac** [comment]
Did you add your authors to `person.yaml` file in `/contents/data/person.yaml` first? That's the "master" file for authors which contains at the very least their name (for instance Marc Aberle) and their slug (marc-aberle). The slug is the value that you should then use in the metadata in your particular resource, and the user will then get the full name (Marc Aberle) displayed.

**Comment by mashalahmad** [comment]
thanks alot now authors is appearing. So do I need to add contributors too in same person.yml too?
