### ISSUE TITLE
[new resource]: Survey of Methods in Computational Literary Studies

### ISSUE THREAD

**Issue by christofs** [DARIAH-ERIC/dariah-campus#980]
### Title of the resource

Survey of Methods in Computational Literary Studies

### Resource type

External Resource

### Authors, editors and contributors

Joanna Byszuk, Julia Dudar, Evegniia Fileva, Andressa Gomide, Lisanne van Rossum, Christof Schöch, Artjoms Šeļa and Karina van Dalen-Oskam

### Topics (keywords)

computational literary studies, genre, authorship, prestige, canon, literary history, survey, introduction

### Learning outcomes

- Gain an overview over key themes, methodological issues and best practices in the field of CLS
- Specifically, understand the fundamentals of issues of authorship attribution, literary history, literary genre, gender in literary studies, and issues of canon and prestige. 
- Gain independence in further exploring the field based on fundamental knowledge and recommended readings and tools. 

### Abstract

The aim of this resource is to document and describe current, widespread research practices in Computational Literary Studies (CLS), based on a large collection of publications that have been published in this field over the last approximately ten years. The perspective of this survey is primarily descriptive: it aims to document current, widespread practices as the authors were able to observe them in the published literature. In this sense, the survey, while far from exhaustive, can also serve as an annotated bibliography of sorts and as a guide to further reading. Despite the fact that this survey is not intended as an introductory textbook, it can also serve as an introduction to several research areas and issues that are prominent within CLS as well as to several key methodological concerns that are of importance when performing research in CLS.

URL: [https://methods.clsinfra.io/](https://methods.clsinfra.io/)

**Comment by christofs** [comment]
Just to note that, in case this resource were found to be of interest for DARIAH Campus, not all contributors need accounts and access to the CMS, just me.

**Comment by VickyGarnett** [comment]
Hi @christofs - I think given that this looks likes it's a CLS-Infra resource, we should probably have a chat about this, as it might need to be in a slightly different format.  I'll email you separately to see about setting up a call :) - Thanks, Vicky

**Comment by VickyGarnett** [comment]
closing as resource published
